version: 2
updates:
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown: 14
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: '/.github/workflows'
    schedule:
      interval: 'daily'
    cooldown: 14

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown: 14
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - '*'
        exclude-patterns:
          - '@hey-api/openapi-ts'
        update-types:
          - 'minor'
          - 'patch'
