version: 2
updates:
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: '/.devops'
    schedule:
      interval: 'daily'

  - package-ecosystem: github-actions
    directory: '/.github/workflows'
    schedule:
      interval: 'daily'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"