applicationName: ladesa-ro-web

deployment:
  replicas: 1
  enabled: false

  containerSecurityContext:
    runAsNonRoot: false
    readOnlyRootFilesystem: false

  ports:
    - containerPort: 3000
      name: web-port

  resources:
    requests:
      cpu: '50m'
      memory: '1Gi'

  readinessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 15
  startupProbe:
    httpGet:
      path: /
      port: 3000
    failureThreshold: 30
    periodSeconds: 10

service:
  enabled: true
  type: NodePort
  ports:
    - name: web-service
      port: 80
      targetPort: web-port

ingress:
  enabled: false
