// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AmbienteCreateData,
  AmbienteCreateErrors,
  AmbienteCreateResponses,
  AmbienteDeleteOneByIdData,
  AmbienteDeleteOneByIdErrors,
  AmbienteDeleteOneByIdResponses,
  AmbienteFindAllData,
  AmbienteFindAllErrors,
  AmbienteFindAllResponses,
  AmbienteFindByIdData,
  AmbienteFindByIdErrors,
  AmbienteFindByIdResponses,
  AmbienteGetDisponibilidadeData,
  AmbienteGetDisponibilidadeErrors,
  AmbienteGetDisponibilidadeResponses,
  AmbienteGetImagemCapaData,
  AmbienteGetImagemCapaErrors,
  AmbienteGetImagemCapaResponses,
  AmbienteListDisponiveisData,
  AmbienteListDisponiveisErrors,
  AmbienteListDisponiveisResponses,
  AmbienteUpdateData,
  AmbienteUpdateErrors,
  AmbienteUpdateImagemCapaData,
  AmbienteUpdateImagemCapaErrors,
  AmbienteUpdateImagemCapaResponses,
  AmbienteUpdateResponses,
  AppControllerGetServiceInfoData,
  AppControllerGetServiceInfoResponses,
  ArquivoFindByIdData,
  ArquivoFindByIdErrors,
  ArquivoFindByIdResponses,
  AutenticacaoLoginData,
  AutenticacaoLoginErrors,
  AutenticacaoLoginResponses,
  AutenticacaoRefreshData,
  AutenticacaoRefreshErrors,
  AutenticacaoRefreshResponses,
  AutenticacaoRequestPasswordResetData,
  AutenticacaoRequestPasswordResetErrors,
  AutenticacaoRequestPasswordResetResponses,
  AutenticacaoSetInitialPasswordData,
  AutenticacaoSetInitialPasswordErrors,
  AutenticacaoSetInitialPasswordResponses,
  AutenticacaoWhoAmIData,
  AutenticacaoWhoAmIEnsinoData,
  AutenticacaoWhoAmIEnsinoErrors,
  AutenticacaoWhoAmIEnsinoResponses,
  AutenticacaoWhoAmIErrors,
  AutenticacaoWhoAmIResponses,
  BlocoCreateData,
  BlocoCreateErrors,
  BlocoCreateResponses,
  BlocoDeleteOneByIdData,
  BlocoDeleteOneByIdErrors,
  BlocoDeleteOneByIdResponses,
  BlocoFindAllData,
  BlocoFindAllErrors,
  BlocoFindAllResponses,
  BlocoFindByIdData,
  BlocoFindByIdErrors,
  BlocoFindByIdResponses,
  BlocoGetImagemCapaData,
  BlocoGetImagemCapaErrors,
  BlocoGetImagemCapaResponses,
  BlocoUpdateData,
  BlocoUpdateErrors,
  BlocoUpdateImagemCapaData,
  BlocoUpdateImagemCapaErrors,
  BlocoUpdateImagemCapaResponses,
  BlocoUpdateResponses,
  CalendarioAgendamentoCreateData,
  CalendarioAgendamentoCreateErrors,
  CalendarioAgendamentoCreateResponses,
  CalendarioAgendamentoDeleteOneByIdData,
  CalendarioAgendamentoDeleteOneByIdErrors,
  CalendarioAgendamentoDeleteOneByIdResponses,
  CalendarioAgendamentoFindByIdData,
  CalendarioAgendamentoFindByIdErrors,
  CalendarioAgendamentoFindByIdResponses,
  CalendarioAgendamentoUpdateData,
  CalendarioAgendamentoUpdateErrors,
  CalendarioAgendamentoUpdateResponses,
  CalendarioLetivoCreateData,
  CalendarioLetivoCreateErrors,
  CalendarioLetivoCreateResponses,
  CalendarioLetivoDeleteOneByIdData,
  CalendarioLetivoDeleteOneByIdErrors,
  CalendarioLetivoDeleteOneByIdResponses,
  CalendarioLetivoDesativarData,
  CalendarioLetivoDesativarErrors,
  CalendarioLetivoDesativarResponses,
  CalendarioLetivoDiaFindAllData,
  CalendarioLetivoDiaFindAllErrors,
  CalendarioLetivoDiaFindAllResponses,
  CalendarioLetivoDiaFindByDataData,
  CalendarioLetivoDiaFindByDataErrors,
  CalendarioLetivoDiaFindByDataResponses,
  CalendarioLetivoDiaUpdateData,
  CalendarioLetivoDiaUpdateErrors,
  CalendarioLetivoDiaUpdateResponses,
  CalendarioLetivoEtapaBulkReplaceData,
  CalendarioLetivoEtapaBulkReplaceErrors,
  CalendarioLetivoEtapaBulkReplaceResponses,
  CalendarioLetivoEtapaFindAllData,
  CalendarioLetivoEtapaFindAllErrors,
  CalendarioLetivoEtapaFindAllResponses,
  CalendarioLetivoFindAllData,
  CalendarioLetivoFindAllErrors,
  CalendarioLetivoFindAllResponses,
  CalendarioLetivoFindByIdData,
  CalendarioLetivoFindByIdErrors,
  CalendarioLetivoFindByIdResponses,
  CalendarioLetivoUpdateData,
  CalendarioLetivoUpdateErrors,
  CalendarioLetivoUpdateResponses,
  CampusCreateData,
  CampusCreateErrors,
  CampusCreateResponses,
  CampusDeleteOneByIdData,
  CampusDeleteOneByIdErrors,
  CampusDeleteOneByIdResponses,
  CampusFindAllData,
  CampusFindAllErrors,
  CampusFindAllResponses,
  CampusFindByIdData,
  CampusFindByIdErrors,
  CampusFindByIdResponses,
  CampusUpdateData,
  CampusUpdateErrors,
  CampusUpdateResponses,
  CidadeFindAllData,
  CidadeFindAllErrors,
  CidadeFindAllResponses,
  CidadeFindByIdData,
  CidadeFindByIdErrors,
  CidadeFindByIdResponses,
  ConsultaAgendamentosPorDataData,
  ConsultaAgendamentosPorDataErrors,
  ConsultaAgendamentosPorDataResponses,
  CursoCreateData,
  CursoCreateErrors,
  CursoCreateResponses,
  CursoDeleteOneByIdData,
  CursoDeleteOneByIdErrors,
  CursoDeleteOneByIdResponses,
  CursoFindAllData,
  CursoFindAllErrors,
  CursoFindAllResponses,
  CursoFindByIdData,
  CursoFindByIdErrors,
  CursoFindByIdResponses,
  CursoGetImagemCapaData,
  CursoGetImagemCapaErrors,
  CursoGetImagemCapaResponses,
  CursoUpdateData,
  CursoUpdateErrors,
  CursoUpdateImagemCapaData,
  CursoUpdateImagemCapaErrors,
  CursoUpdateImagemCapaResponses,
  CursoUpdateResponses,
  DiarioBatchCreateData,
  DiarioBatchCreateErrors,
  DiarioBatchCreateResponses,
  DiarioCreateData,
  DiarioCreateErrors,
  DiarioCreateResponses,
  DiarioDeleteOneByIdData,
  DiarioDeleteOneByIdErrors,
  DiarioDeleteOneByIdResponses,
  DiarioFindAllData,
  DiarioFindAllErrors,
  DiarioFindAllResponses,
  DiarioFindByIdData,
  DiarioFindByIdErrors,
  DiarioFindByIdResponses,
  DiarioPreferenciaAgrupamentoBulkReplaceData,
  DiarioPreferenciaAgrupamentoBulkReplaceErrors,
  DiarioPreferenciaAgrupamentoBulkReplaceResponses,
  DiarioPreferenciaAgrupamentoFindAllData,
  DiarioPreferenciaAgrupamentoFindAllErrors,
  DiarioPreferenciaAgrupamentoFindAllResponses,
  DiarioProfessorBulkReplaceData,
  DiarioProfessorBulkReplaceErrors,
  DiarioProfessorBulkReplaceResponses,
  DiarioProfessorFindAllData,
  DiarioProfessorFindAllErrors,
  DiarioProfessorFindAllResponses,
  DiarioUpdateData,
  DiarioUpdateErrors,
  DiarioUpdateResponses,
  DisciplinaCreateData,
  DisciplinaCreateErrors,
  DisciplinaCreateResponses,
  DisciplinaDeleteOneByIdData,
  DisciplinaDeleteOneByIdErrors,
  DisciplinaDeleteOneByIdResponses,
  DisciplinaFindAllData,
  DisciplinaFindAllErrors,
  DisciplinaFindAllResponses,
  DisciplinaFindByIdData,
  DisciplinaFindByIdErrors,
  DisciplinaFindByIdResponses,
  DisciplinaGetImagemCapaData,
  DisciplinaGetImagemCapaErrors,
  DisciplinaGetImagemCapaResponses,
  DisciplinaUpdateData,
  DisciplinaUpdateErrors,
  DisciplinaUpdateImagemCapaData,
  DisciplinaUpdateImagemCapaErrors,
  DisciplinaUpdateImagemCapaResponses,
  DisciplinaUpdateResponses,
  EmpresaCreateData,
  EmpresaCreateErrors,
  EmpresaCreateResponses,
  EmpresaDeleteOneByIdData,
  EmpresaDeleteOneByIdErrors,
  EmpresaDeleteOneByIdResponses,
  EmpresaFindAllData,
  EmpresaFindAllErrors,
  EmpresaFindAllResponses,
  EmpresaFindByIdData,
  EmpresaFindByIdErrors,
  EmpresaFindByIdResponses,
  EmpresaUpdateData,
  EmpresaUpdateErrors,
  EmpresaUpdateResponses,
  EstadoFindAllData,
  EstadoFindAllErrors,
  EstadoFindAllResponses,
  EstadoFindByIdData,
  EstadoFindByIdErrors,
  EstadoFindByIdResponses,
  EstagiarioCreateData,
  EstagiarioCreateErrors,
  EstagiarioCreateResponses,
  EstagiarioDeleteOneByIdData,
  EstagiarioDeleteOneByIdErrors,
  EstagiarioDeleteOneByIdResponses,
  EstagiarioFindAllData,
  EstagiarioFindAllErrors,
  EstagiarioFindAllResponses,
  EstagiarioFindByIdData,
  EstagiarioFindByIdErrors,
  EstagiarioFindByIdResponses,
  EstagiarioUpdateData,
  EstagiarioUpdateErrors,
  EstagiarioUpdateResponses,
  EstagioCreateData,
  EstagioCreateErrors,
  EstagioCreateResponses,
  EstagioDeleteData,
  EstagioDeleteErrors,
  EstagioDeleteResponses,
  EstagioFindAllData,
  EstagioFindAllErrors,
  EstagioFindAllResponses,
  EstagioFindByIdData,
  EstagioFindByIdErrors,
  EstagioFindByIdResponses,
  EstagioUpdateData,
  EstagioUpdateErrors,
  EstagioUpdateResponses,
  GerarHorarioAceitarData,
  GerarHorarioAceitarErrors,
  GerarHorarioAceitarResponses,
  GerarHorarioCreateData,
  GerarHorarioCreateErrors,
  GerarHorarioCreateResponses,
  GerarHorarioFindByIdData,
  GerarHorarioFindByIdErrors,
  GerarHorarioFindByIdResponses,
  GerarHorarioRejeitarData,
  GerarHorarioRejeitarErrors,
  GerarHorarioRejeitarResponses,
  GradeHorariaFindByCampusData,
  GradeHorariaFindByCampusErrors,
  GradeHorariaFindByCampusResponses,
  GradeHorariaReplaceData,
  GradeHorariaReplaceErrors,
  GradeHorariaReplaceResponses,
  HorarioEdicaoApplyChangeData,
  HorarioEdicaoApplyChangeErrors,
  HorarioEdicaoApplyChangeResponses,
  HorarioEdicaoCancelarData,
  HorarioEdicaoCancelarErrors,
  HorarioEdicaoCancelarResponses,
  HorarioEdicaoCreateData,
  HorarioEdicaoCreateErrors,
  HorarioEdicaoCreateResponses,
  HorarioEdicaoSalvarData,
  HorarioEdicaoSalvarErrors,
  HorarioEdicaoSalvarResponses,
  HorarioMescladoData,
  HorarioMescladoErrors,
  HorarioMescladoResponses,
  ModalidadeCreateData,
  ModalidadeCreateErrors,
  ModalidadeCreateResponses,
  ModalidadeDeleteOneByIdData,
  ModalidadeDeleteOneByIdErrors,
  ModalidadeDeleteOneByIdResponses,
  ModalidadeFindAllData,
  ModalidadeFindAllErrors,
  ModalidadeFindAllResponses,
  ModalidadeFindByIdData,
  ModalidadeFindByIdErrors,
  ModalidadeFindByIdResponses,
  ModalidadeGetImagemCapaData,
  ModalidadeGetImagemCapaErrors,
  ModalidadeGetImagemCapaResponses,
  ModalidadeUpdateData,
  ModalidadeUpdateErrors,
  ModalidadeUpdateImagemCapaData,
  ModalidadeUpdateImagemCapaErrors,
  ModalidadeUpdateImagemCapaResponses,
  ModalidadeUpdateResponses,
  NivelFormacaoCreateData,
  NivelFormacaoCreateErrors,
  NivelFormacaoCreateResponses,
  NivelFormacaoDeleteOneByIdData,
  NivelFormacaoDeleteOneByIdErrors,
  NivelFormacaoDeleteOneByIdResponses,
  NivelFormacaoFindAllData,
  NivelFormacaoFindAllErrors,
  NivelFormacaoFindAllResponses,
  NivelFormacaoFindByIdData,
  NivelFormacaoFindByIdErrors,
  NivelFormacaoFindByIdResponses,
  NivelFormacaoGetImagemCapaData,
  NivelFormacaoGetImagemCapaErrors,
  NivelFormacaoGetImagemCapaResponses,
  NivelFormacaoUpdateData,
  NivelFormacaoUpdateErrors,
  NivelFormacaoUpdateImagemCapaData,
  NivelFormacaoUpdateImagemCapaErrors,
  NivelFormacaoUpdateImagemCapaResponses,
  NivelFormacaoUpdateResponses,
  NotificacaoContagemNaoLidasData,
  NotificacaoContagemNaoLidasErrors,
  NotificacaoContagemNaoLidasResponses,
  NotificacaoFindAllData,
  NotificacaoFindAllErrors,
  NotificacaoFindAllResponses,
  NotificacaoMarcarLidaData,
  NotificacaoMarcarLidaErrors,
  NotificacaoMarcarLidaResponses,
  OfertaFormacaoCreateData,
  OfertaFormacaoCreateErrors,
  OfertaFormacaoCreateResponses,
  OfertaFormacaoDeleteOneByIdData,
  OfertaFormacaoDeleteOneByIdErrors,
  OfertaFormacaoDeleteOneByIdResponses,
  OfertaFormacaoFindAllData,
  OfertaFormacaoFindAllErrors,
  OfertaFormacaoFindAllResponses,
  OfertaFormacaoFindByIdData,
  OfertaFormacaoFindByIdErrors,
  OfertaFormacaoFindByIdResponses,
  OfertaFormacaoUpdateData,
  OfertaFormacaoUpdateErrors,
  OfertaFormacaoUpdateResponses,
  PerfilEnsinoByIdData,
  PerfilEnsinoByIdErrors,
  PerfilEnsinoByIdResponses,
  PerfilFindById2Data,
  PerfilFindById2Errors,
  PerfilFindById2Responses,
  PerfilFindByIdData,
  PerfilFindByIdErrors,
  PerfilFindByIdResponses,
  PerfilListData,
  PerfilListErrors,
  PerfilListResponses,
  RelatorioAulasMinistradasData,
  RelatorioAulasMinistradasErrors,
  RelatorioAulasMinistradasPdfData,
  RelatorioAulasMinistradasPdfErrors,
  RelatorioAulasMinistradasResponses,
  TurmaCreateData,
  TurmaCreateErrors,
  TurmaCreateResponses,
  TurmaDeleteOneByIdData,
  TurmaDeleteOneByIdErrors,
  TurmaDeleteOneByIdResponses,
  TurmaDiarioConfigurarData,
  TurmaDiarioConfigurarErrors,
  TurmaDiarioConfigurarResponses,
  TurmaDisponibilidadeDeactivateData,
  TurmaDisponibilidadeDeactivateErrors,
  TurmaDisponibilidadeDeactivateResponses,
  TurmaDisponibilidadeFindAllActiveData,
  TurmaDisponibilidadeFindAllActiveErrors,
  TurmaDisponibilidadeFindAllActiveResponses,
  TurmaDisponibilidadeFindByWeekData,
  TurmaDisponibilidadeFindByWeekErrors,
  TurmaDisponibilidadeFindByWeekResponses,
  TurmaDisponibilidadeSaveData,
  TurmaDisponibilidadeSaveErrors,
  TurmaDisponibilidadeSaveResponses,
  TurmaEventoCreateData,
  TurmaEventoCreateErrors,
  TurmaEventoCreateResponses,
  TurmaEventoDeleteData,
  TurmaEventoDeleteErrors,
  TurmaEventoDeleteResponses,
  TurmaEventoFindAllData,
  TurmaEventoFindAllErrors,
  TurmaEventoFindAllResponses,
  TurmaEventoUpdateData,
  TurmaEventoUpdateErrors,
  TurmaEventoUpdateResponses,
  TurmaFindAllData,
  TurmaFindAllErrors,
  TurmaFindAllResponses,
  TurmaFindByIdData,
  TurmaFindByIdErrors,
  TurmaFindByIdResponses,
  TurmaGetImagemCapaData,
  TurmaGetImagemCapaErrors,
  TurmaGetImagemCapaResponses,
  TurmaHorarioSemanalData,
  TurmaHorarioSemanalErrors,
  TurmaHorarioSemanalResponses,
  TurmaUpdateData,
  TurmaUpdateErrors,
  TurmaUpdateImagemCapaData,
  TurmaUpdateImagemCapaErrors,
  TurmaUpdateImagemCapaResponses,
  TurmaUpdateResponses,
  UsuarioCreateData,
  UsuarioCreateErrors,
  UsuarioCreateResponses,
  UsuarioDeleteOneByIdData,
  UsuarioDeleteOneByIdErrors,
  UsuarioDeleteOneByIdResponses,
  UsuarioDisponibilidadeData,
  UsuarioDisponibilidadeErrors,
  UsuarioDisponibilidadeResponses,
  UsuarioEnsinoByIdData,
  UsuarioEnsinoByIdErrors,
  UsuarioEnsinoByIdResponses,
  UsuarioEventoCreateData,
  UsuarioEventoCreateErrors,
  UsuarioEventoCreateResponses,
  UsuarioEventoDeleteData,
  UsuarioEventoDeleteErrors,
  UsuarioEventoDeleteResponses,
  UsuarioEventoFindAllData,
  UsuarioEventoFindAllErrors,
  UsuarioEventoFindAllResponses,
  UsuarioEventoUpdateData,
  UsuarioEventoUpdateErrors,
  UsuarioEventoUpdateResponses,
  UsuarioFindAllData,
  UsuarioFindAllErrors,
  UsuarioFindAllResponses,
  UsuarioFindByIdData,
  UsuarioFindByIdErrors,
  UsuarioFindByIdResponses,
  UsuarioGetImagemCapaData,
  UsuarioGetImagemCapaErrors,
  UsuarioGetImagemCapaResponses,
  UsuarioGetImagemPerfilData,
  UsuarioGetImagemPerfilErrors,
  UsuarioGetImagemPerfilResponses,
  UsuarioHorarioSemanalData,
  UsuarioHorarioSemanalErrors,
  UsuarioHorarioSemanalResponses,
  UsuarioSetDisponibilidadeData,
  UsuarioSetDisponibilidadeErrors,
  UsuarioSetDisponibilidadeResponses,
  UsuarioUpdateData,
  UsuarioUpdateErrors,
  UsuarioUpdateImagemCapaData,
  UsuarioUpdateImagemCapaErrors,
  UsuarioUpdateImagemCapaResponses,
  UsuarioUpdateImagemPerfilData,
  UsuarioUpdateImagemPerfilErrors,
  UsuarioUpdateImagemPerfilResponses,
  UsuarioUpdateResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Informações do serviço
 */
export const appControllerGetServiceInfo = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AppControllerGetServiceInfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AppControllerGetServiceInfoResponses,
    unknown,
    ThrowOnError
  >({ url: '/', ...options });

/**
 * Lista modalidades
 *
 * Lista modalidades
 */
export const modalidadeFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<ModalidadeFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ModalidadeFindAllResponses,
    ModalidadeFindAllErrors,
    ThrowOnError
  >({ url: '/modalidades', ...options });

/**
 * Cria uma modalidade
 *
 * Cria uma modalidade
 */
export const modalidadeCreate = <ThrowOnError extends boolean = false>(
  options: Options<ModalidadeCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ModalidadeCreateResponses,
    ModalidadeCreateErrors,
    ThrowOnError
  >({
    url: '/modalidades',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove uma modalidade
 *
 * Remove uma modalidade
 */
export const modalidadeDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<ModalidadeDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ModalidadeDeleteOneByIdResponses,
    ModalidadeDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/modalidades/{id}', ...options });

/**
 * Busca uma modalidade por ID
 *
 * Busca uma modalidade por ID
 */
export const modalidadeFindById = <ThrowOnError extends boolean = false>(
  options: Options<ModalidadeFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ModalidadeFindByIdResponses,
    ModalidadeFindByIdErrors,
    ThrowOnError
  >({ url: '/modalidades/{id}', ...options });

/**
 * Atualiza uma modalidade
 *
 * Atualiza uma modalidade
 */
export const modalidadeUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ModalidadeUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    ModalidadeUpdateResponses,
    ModalidadeUpdateErrors,
    ThrowOnError
  >({
    url: '/modalidades/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Obtem a imagem de capa de uma modalidade
 *
 * Obtem a imagem de capa de uma modalidade
 */
export const modalidadeGetImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<ModalidadeGetImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ModalidadeGetImagemCapaResponses,
    ModalidadeGetImagemCapaErrors,
    ThrowOnError
  >({ url: '/modalidades/{id}/imagem/capa', ...options });

/**
 * Define a imagem de capa de uma modalidade
 *
 * Define a imagem de capa de uma modalidade
 */
export const modalidadeUpdateImagemCapa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ModalidadeUpdateImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ModalidadeUpdateImagemCapaResponses,
    ModalidadeUpdateImagemCapaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/modalidades/{id}/imagem/capa',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Busca um arquivo por ID
 *
 * Busca um arquivo por ID
 */
export const arquivoFindById = <ThrowOnError extends boolean = false>(
  options: Options<ArquivoFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ArquivoFindByIdResponses,
    ArquivoFindByIdErrors,
    ThrowOnError
  >({ url: '/arquivos/{id}', ...options });

/**
 * Lista cursos
 *
 * Lista cursos
 */
export const cursoFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<CursoFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    CursoFindAllResponses,
    CursoFindAllErrors,
    ThrowOnError
  >({ url: '/cursos', ...options });

/**
 * Cria um curso
 *
 * Cria um curso
 */
export const cursoCreate = <ThrowOnError extends boolean = false>(
  options: Options<CursoCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CursoCreateResponses,
    CursoCreateErrors,
    ThrowOnError
  >({
    url: '/cursos',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove um curso
 *
 * Remove um curso
 */
export const cursoDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<CursoDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    CursoDeleteOneByIdResponses,
    CursoDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/cursos/{id}', ...options });

/**
 * Busca um curso por ID
 *
 * Busca um curso por ID
 */
export const cursoFindById = <ThrowOnError extends boolean = false>(
  options: Options<CursoFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CursoFindByIdResponses,
    CursoFindByIdErrors,
    ThrowOnError
  >({ url: '/cursos/{id}', ...options });

/**
 * Atualiza um curso
 *
 * Atualiza um curso
 */
export const cursoUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CursoUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    CursoUpdateResponses,
    CursoUpdateErrors,
    ThrowOnError
  >({
    url: '/cursos/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Busca imagem de capa de um curso
 *
 * Busca imagem de capa de um curso
 */
export const cursoGetImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<CursoGetImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CursoGetImagemCapaResponses,
    CursoGetImagemCapaErrors,
    ThrowOnError
  >({ url: '/cursos/{id}/imagem/capa', ...options });

/**
 * Define imagem de capa de um curso
 *
 * Define imagem de capa de um curso
 */
export const cursoUpdateImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<CursoUpdateImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).put<
    CursoUpdateImagemCapaResponses,
    CursoUpdateImagemCapaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/cursos/{id}/imagem/capa',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Lista campi
 *
 * Lista campi
 */
export const campusFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<CampusFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    CampusFindAllResponses,
    CampusFindAllErrors,
    ThrowOnError
  >({ url: '/campi', ...options });

/**
 * Cria um campus
 *
 * Cria um campus
 */
export const campusCreate = <ThrowOnError extends boolean = false>(
  options: Options<CampusCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CampusCreateResponses,
    CampusCreateErrors,
    ThrowOnError
  >({
    url: '/campi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove um campus
 *
 * Remove um campus
 */
export const campusDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<CampusDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    CampusDeleteOneByIdResponses,
    CampusDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/campi/{id}', ...options });

/**
 * Busca um campus por ID
 *
 * Busca um campus por ID
 */
export const campusFindById = <ThrowOnError extends boolean = false>(
  options: Options<CampusFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CampusFindByIdResponses,
    CampusFindByIdErrors,
    ThrowOnError
  >({ url: '/campi/{id}', ...options });

/**
 * Atualiza um campus
 *
 * Atualiza um campus
 */
export const campusUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CampusUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    CampusUpdateResponses,
    CampusUpdateErrors,
    ThrowOnError
  >({
    url: '/campi/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista ofertas de formacao
 *
 * Lista ofertas de formacao
 */
export const ofertaFormacaoFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<OfertaFormacaoFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    OfertaFormacaoFindAllResponses,
    OfertaFormacaoFindAllErrors,
    ThrowOnError
  >({ url: '/ofertas-formacoes', ...options });

/**
 * Cria uma oferta de formacao
 *
 * Cria uma oferta de formacao
 */
export const ofertaFormacaoCreate = <ThrowOnError extends boolean = false>(
  options: Options<OfertaFormacaoCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    OfertaFormacaoCreateResponses,
    OfertaFormacaoCreateErrors,
    ThrowOnError
  >({
    url: '/ofertas-formacoes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove uma oferta de formacao
 *
 * Remove uma oferta de formacao
 */
export const ofertaFormacaoDeleteOneById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OfertaFormacaoDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    OfertaFormacaoDeleteOneByIdResponses,
    OfertaFormacaoDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/ofertas-formacoes/{id}', ...options });

/**
 * Busca uma oferta de formacao por ID
 *
 * Busca uma oferta de formacao por ID
 */
export const ofertaFormacaoFindById = <ThrowOnError extends boolean = false>(
  options: Options<OfertaFormacaoFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    OfertaFormacaoFindByIdResponses,
    OfertaFormacaoFindByIdErrors,
    ThrowOnError
  >({ url: '/ofertas-formacoes/{id}', ...options });

/**
 * Atualiza uma oferta de formacao
 *
 * Atualiza uma oferta de formacao
 */
export const ofertaFormacaoUpdate = <ThrowOnError extends boolean = false>(
  options: Options<OfertaFormacaoUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    OfertaFormacaoUpdateResponses,
    OfertaFormacaoUpdateErrors,
    ThrowOnError
  >({
    url: '/ofertas-formacoes/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista niveis de formacao
 *
 * Lista niveis de formacao
 */
export const nivelFormacaoFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<NivelFormacaoFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    NivelFormacaoFindAllResponses,
    NivelFormacaoFindAllErrors,
    ThrowOnError
  >({ url: '/niveis-formacoes', ...options });

/**
 * Cria um nivel de formacao
 *
 * Cria um nivel de formacao
 */
export const nivelFormacaoCreate = <ThrowOnError extends boolean = false>(
  options: Options<NivelFormacaoCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    NivelFormacaoCreateResponses,
    NivelFormacaoCreateErrors,
    ThrowOnError
  >({
    url: '/niveis-formacoes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove um nivel de formacao
 *
 * Remove um nivel de formacao
 */
export const nivelFormacaoDeleteOneById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<NivelFormacaoDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    NivelFormacaoDeleteOneByIdResponses,
    NivelFormacaoDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/niveis-formacoes/{id}', ...options });

/**
 * Busca um nivel de formacao por ID
 *
 * Busca um nivel de formacao por ID
 */
export const nivelFormacaoFindById = <ThrowOnError extends boolean = false>(
  options: Options<NivelFormacaoFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    NivelFormacaoFindByIdResponses,
    NivelFormacaoFindByIdErrors,
    ThrowOnError
  >({ url: '/niveis-formacoes/{id}', ...options });

/**
 * Atualiza um nivel de formacao
 *
 * Atualiza um nivel de formacao
 */
export const nivelFormacaoUpdate = <ThrowOnError extends boolean = false>(
  options: Options<NivelFormacaoUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    NivelFormacaoUpdateResponses,
    NivelFormacaoUpdateErrors,
    ThrowOnError
  >({
    url: '/niveis-formacoes/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Obtem a imagem de capa de um nivel de formacao
 *
 * Obtem a imagem de capa de um nivel de formacao
 */
export const nivelFormacaoGetImagemCapa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<NivelFormacaoGetImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).get<
    NivelFormacaoGetImagemCapaResponses,
    NivelFormacaoGetImagemCapaErrors,
    ThrowOnError
  >({ url: '/niveis-formacoes/{id}/imagem/capa', ...options });

/**
 * Define a imagem de capa de um nivel de formacao
 *
 * Define a imagem de capa de um nivel de formacao
 */
export const nivelFormacaoUpdateImagemCapa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<NivelFormacaoUpdateImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).put<
    NivelFormacaoUpdateImagemCapaResponses,
    NivelFormacaoUpdateImagemCapaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/niveis-formacoes/{id}/imagem/capa',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Lista usuarios
 *
 * Lista usuarios
 */
export const usuarioFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UsuarioFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    UsuarioFindAllResponses,
    UsuarioFindAllErrors,
    ThrowOnError
  >({ url: '/usuarios', ...options });

/**
 * Cria um usuario
 *
 * Cria um usuario
 */
export const usuarioCreate = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UsuarioCreateResponses,
    UsuarioCreateErrors,
    ThrowOnError
  >({
    url: '/usuarios',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove um usuario
 *
 * Remove um usuario
 */
export const usuarioDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UsuarioDeleteOneByIdResponses,
    UsuarioDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}', ...options });

/**
 * Busca um usuario por ID
 *
 * Busca um usuario por ID
 */
export const usuarioFindById = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UsuarioFindByIdResponses,
    UsuarioFindByIdErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}', ...options });

/**
 * Atualiza um usuario
 *
 * Atualiza um usuario
 */
export const usuarioUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UsuarioUpdateResponses,
    UsuarioUpdateErrors,
    ThrowOnError
  >({
    url: '/usuarios/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Busca dados de ensino de um usuario (disciplinas, cursos e turmas onde leciona)
 *
 * Busca dados de ensino de um usuario (disciplinas, cursos e turmas onde leciona)
 */
export const usuarioEnsinoById = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioEnsinoByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UsuarioEnsinoByIdResponses,
    UsuarioEnsinoByIdErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}/ensino', ...options });

/**
 * Consulta horario semanal de um usuario (professor)
 *
 * Consulta horario semanal de um usuario (professor)
 */
export const usuarioHorarioSemanal = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioHorarioSemanalData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UsuarioHorarioSemanalResponses,
    UsuarioHorarioSemanalErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}/horario', ...options });

/**
 * Consulta grade de disponibilidade de um usuario por campus
 *
 * Consulta grade de disponibilidade de um usuario por campus
 */
export const usuarioDisponibilidade = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioDisponibilidadeData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UsuarioDisponibilidadeResponses,
    UsuarioDisponibilidadeErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}/disponibilidade', ...options });

/**
 * Define grade de disponibilidade de um usuario por campus (bulk replace)
 *
 * Define grade de disponibilidade de um usuario por campus (bulk replace)
 */
export const usuarioSetDisponibilidade = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioSetDisponibilidadeData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UsuarioSetDisponibilidadeResponses,
    UsuarioSetDisponibilidadeErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}/disponibilidade', ...options });

/**
 * Busca imagem de capa de um usuario
 *
 * Busca imagem de capa de um usuario
 */
export const usuarioGetImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioGetImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UsuarioGetImagemCapaResponses,
    UsuarioGetImagemCapaErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}/imagem/capa', ...options });

/**
 * Define imagem de capa de um usuario
 *
 * Define imagem de capa de um usuario
 */
export const usuarioUpdateImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioUpdateImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UsuarioUpdateImagemCapaResponses,
    UsuarioUpdateImagemCapaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/usuarios/{id}/imagem/capa',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Busca imagem de perfil de um usuario
 *
 * Busca imagem de perfil de um usuario
 */
export const usuarioGetImagemPerfil = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioGetImagemPerfilData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UsuarioGetImagemPerfilResponses,
    UsuarioGetImagemPerfilErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}/imagem/perfil', ...options });

/**
 * Define imagem de perfil de um usuario
 *
 * Define imagem de perfil de um usuario
 */
export const usuarioUpdateImagemPerfil = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioUpdateImagemPerfilData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UsuarioUpdateImagemPerfilResponses,
    UsuarioUpdateImagemPerfilErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/usuarios/{id}/imagem/perfil',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Lista eventos/agenda do usuario (professor)
 */
export const usuarioEventoFindAll = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioEventoFindAllData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UsuarioEventoFindAllResponses,
    UsuarioEventoFindAllErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}/eventos', ...options });

/**
 * Cria evento/indisponibilidade escopado ao usuario
 */
export const usuarioEventoCreate = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioEventoCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UsuarioEventoCreateResponses,
    UsuarioEventoCreateErrors,
    ThrowOnError
  >({
    url: '/usuarios/{id}/eventos',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove evento do usuario
 */
export const usuarioEventoDelete = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioEventoDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UsuarioEventoDeleteResponses,
    UsuarioEventoDeleteErrors,
    ThrowOnError
  >({ url: '/usuarios/{id}/eventos/{eventoId}', ...options });

/**
 * Atualiza evento do usuario
 */
export const usuarioEventoUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UsuarioEventoUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UsuarioEventoUpdateResponses,
    UsuarioEventoUpdateErrors,
    ThrowOnError
  >({
    url: '/usuarios/{id}/eventos/{eventoId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista perfis com paginação e filtros
 *
 * Lista perfis com paginação e filtros
 */
export const perfilList = <ThrowOnError extends boolean = false>(
  options?: Options<PerfilListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    PerfilListResponses,
    PerfilListErrors,
    ThrowOnError
  >({ url: '/perfis', ...options });

/**
 * Busca um perfil por ID
 *
 * Busca um perfil por ID
 */
export const perfilFindById = <ThrowOnError extends boolean = false>(
  options: Options<PerfilFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    PerfilFindByIdResponses,
    PerfilFindByIdErrors,
    ThrowOnError
  >({ url: '/perfis/{id}', ...options });

/**
 * Busca um perfil por ID
 *
 * Busca um perfil por ID
 */
export const perfilFindById2 = <ThrowOnError extends boolean = false>(
  options: Options<PerfilFindById2Data, ThrowOnError>
) =>
  (options.client ?? client).get<
    PerfilFindById2Responses,
    PerfilFindById2Errors,
    ThrowOnError
  >({ url: '/usuarios/{usuarioId}/perfis/{id}', ...options });

/**
 * Busca dados de ensino de um perfil
 *
 * Busca dados de ensino de um perfil
 */
export const perfilEnsinoById = <ThrowOnError extends boolean = false>(
  options: Options<PerfilEnsinoByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    PerfilEnsinoByIdResponses,
    PerfilEnsinoByIdErrors,
    ThrowOnError
  >({ url: '/usuarios/{usuarioId}/perfis/{id}/ensino', ...options });

/**
 * Consulta horario mesclado de multiplas turmas
 *
 * Consulta horario mesclado de multiplas turmas
 */
export const horarioMesclado = <ThrowOnError extends boolean = false>(
  options: Options<HorarioMescladoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    HorarioMescladoResponses,
    HorarioMescladoErrors,
    ThrowOnError
  >({ url: '/horarios/mesclado', ...options });

/**
 * Lista disciplinas
 *
 * Lista disciplinas
 */
export const disciplinaFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<DisciplinaFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    DisciplinaFindAllResponses,
    DisciplinaFindAllErrors,
    ThrowOnError
  >({ url: '/disciplinas', ...options });

/**
 * Cria uma disciplina
 *
 * Cria uma disciplina
 */
export const disciplinaCreate = <ThrowOnError extends boolean = false>(
  options: Options<DisciplinaCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    DisciplinaCreateResponses,
    DisciplinaCreateErrors,
    ThrowOnError
  >({
    url: '/disciplinas',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove uma disciplina
 *
 * Remove uma disciplina
 */
export const disciplinaDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<DisciplinaDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DisciplinaDeleteOneByIdResponses,
    DisciplinaDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/disciplinas/{id}', ...options });

/**
 * Busca uma disciplina por ID
 *
 * Busca uma disciplina por ID
 */
export const disciplinaFindById = <ThrowOnError extends boolean = false>(
  options: Options<DisciplinaFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    DisciplinaFindByIdResponses,
    DisciplinaFindByIdErrors,
    ThrowOnError
  >({ url: '/disciplinas/{id}', ...options });

/**
 * Atualiza uma disciplina
 *
 * Atualiza uma disciplina
 */
export const disciplinaUpdate = <ThrowOnError extends boolean = false>(
  options: Options<DisciplinaUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    DisciplinaUpdateResponses,
    DisciplinaUpdateErrors,
    ThrowOnError
  >({
    url: '/disciplinas/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Busca imagem de capa de uma disciplina
 *
 * Busca imagem de capa de uma disciplina
 */
export const disciplinaGetImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<DisciplinaGetImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).get<
    DisciplinaGetImagemCapaResponses,
    DisciplinaGetImagemCapaErrors,
    ThrowOnError
  >({ url: '/disciplinas/{id}/imagem/capa', ...options });

/**
 * Define imagem de capa de uma disciplina
 *
 * Define imagem de capa de uma disciplina
 */
export const disciplinaUpdateImagemCapa = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DisciplinaUpdateImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).put<
    DisciplinaUpdateImagemCapaResponses,
    DisciplinaUpdateImagemCapaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/disciplinas/{id}/imagem/capa',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Remove um agendamento do calendario
 *
 * Remove um agendamento do calendario
 */
export const calendarioAgendamentoDeleteOneById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioAgendamentoDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    CalendarioAgendamentoDeleteOneByIdResponses,
    CalendarioAgendamentoDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/calendario/agendamentos/{id}', ...options });

/**
 * Busca um agendamento por ID
 *
 * Busca um agendamento por ID
 */
export const calendarioAgendamentoFindById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioAgendamentoFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CalendarioAgendamentoFindByIdResponses,
    CalendarioAgendamentoFindByIdErrors,
    ThrowOnError
  >({ url: '/calendario/agendamentos/{id}', ...options });

/**
 * Atualiza um agendamento do calendario
 *
 * Atualiza um agendamento do calendario
 */
export const calendarioAgendamentoUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioAgendamentoUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    CalendarioAgendamentoUpdateResponses,
    CalendarioAgendamentoUpdateErrors,
    ThrowOnError
  >({
    url: '/calendario/agendamentos/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Cria um agendamento no calendario
 *
 * Cria um agendamento no calendario
 */
export const calendarioAgendamentoCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioAgendamentoCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CalendarioAgendamentoCreateResponses,
    CalendarioAgendamentoCreateErrors,
    ThrowOnError
  >({
    url: '/calendario/agendamentos',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Consulta agendamentos por período
 *
 * Consulta agendamentos por período
 */
export const consultaAgendamentosPorData = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ConsultaAgendamentosPorDataData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ConsultaAgendamentosPorDataResponses,
    ConsultaAgendamentosPorDataErrors,
    ThrowOnError
  >({ url: '/calendario/consultas/agendamentos', ...options });

/**
 * Lista calendarios letivos
 *
 * Lista calendarios letivos
 */
export const calendarioLetivoFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<CalendarioLetivoFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    CalendarioLetivoFindAllResponses,
    CalendarioLetivoFindAllErrors,
    ThrowOnError
  >({ url: '/calendarios-letivos', ...options });

/**
 * Cria um calendario letivo
 *
 * Cria um calendario letivo
 */
export const calendarioLetivoCreate = <ThrowOnError extends boolean = false>(
  options: Options<CalendarioLetivoCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CalendarioLetivoCreateResponses,
    CalendarioLetivoCreateErrors,
    ThrowOnError
  >({
    url: '/calendarios-letivos',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove um calendario letivo
 *
 * Remove um calendario letivo
 */
export const calendarioLetivoDeleteOneById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioLetivoDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    CalendarioLetivoDeleteOneByIdResponses,
    CalendarioLetivoDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/calendarios-letivos/{id}', ...options });

/**
 * Busca um calendario letivo por ID
 *
 * Busca um calendario letivo por ID
 */
export const calendarioLetivoFindById = <ThrowOnError extends boolean = false>(
  options: Options<CalendarioLetivoFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CalendarioLetivoFindByIdResponses,
    CalendarioLetivoFindByIdErrors,
    ThrowOnError
  >({ url: '/calendarios-letivos/{id}', ...options });

/**
 * Atualiza um calendario letivo
 *
 * Atualiza um calendario letivo
 */
export const calendarioLetivoUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CalendarioLetivoUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    CalendarioLetivoUpdateResponses,
    CalendarioLetivoUpdateErrors,
    ThrowOnError
  >({
    url: '/calendarios-letivos/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista dias de um calendario letivo
 *
 * Lista dias de um calendario letivo
 */
export const calendarioLetivoDiaFindAll = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioLetivoDiaFindAllData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CalendarioLetivoDiaFindAllResponses,
    CalendarioLetivoDiaFindAllErrors,
    ThrowOnError
  >({ url: '/calendarios-letivos/{calendarioLetivoId}/dias', ...options });

/**
 * Busca um dia de calendario por data (YYYY-MM-DD)
 *
 * Busca um dia de calendario por data (YYYY-MM-DD)
 */
export const calendarioLetivoDiaFindByData = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioLetivoDiaFindByDataData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CalendarioLetivoDiaFindByDataResponses,
    CalendarioLetivoDiaFindByDataErrors,
    ThrowOnError
  >({
    url: '/calendarios-letivos/{calendarioLetivoId}/dias/{data}',
    ...options,
  });

/**
 * Atualiza um dia de calendario
 *
 * Atualiza um dia de calendario
 */
export const calendarioLetivoDiaUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CalendarioLetivoDiaUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    CalendarioLetivoDiaUpdateResponses,
    CalendarioLetivoDiaUpdateErrors,
    ThrowOnError
  >({
    url: '/calendarios-letivos/{calendarioLetivoId}/dias/{data}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista etapas do calendario letivo
 *
 * Lista etapas do calendario letivo
 */
export const calendarioLetivoEtapaFindAll = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioLetivoEtapaFindAllData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CalendarioLetivoEtapaFindAllResponses,
    CalendarioLetivoEtapaFindAllErrors,
    ThrowOnError
  >({ url: '/calendarios-letivos/{calendarioLetivoId}/etapas', ...options });

/**
 * Substitui datas das etapas do calendario letivo
 *
 * Substitui datas das etapas do calendario letivo
 */
export const calendarioLetivoEtapaBulkReplace = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CalendarioLetivoEtapaBulkReplaceData, ThrowOnError>
) =>
  (options.client ?? client).put<
    CalendarioLetivoEtapaBulkReplaceResponses,
    CalendarioLetivoEtapaBulkReplaceErrors,
    ThrowOnError
  >({
    url: '/calendarios-letivos/{calendarioLetivoId}/etapas',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Desativa um calendario letivo (sem excluir)
 *
 * Desativa um calendario letivo (sem excluir)
 */
export const calendarioLetivoDesativar = <ThrowOnError extends boolean = false>(
  options: Options<CalendarioLetivoDesativarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CalendarioLetivoDesativarResponses,
    CalendarioLetivoDesativarErrors,
    ThrowOnError
  >({ url: '/calendarios-letivos/{id}/desativar', ...options });

/**
 * Lista cidades
 *
 * Lista cidades
 */
export const cidadeFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<CidadeFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    CidadeFindAllResponses,
    CidadeFindAllErrors,
    ThrowOnError
  >({ url: '/base/cidades', ...options });

/**
 * Busca uma cidade por ID
 *
 * Busca uma cidade por ID
 */
export const cidadeFindById = <ThrowOnError extends boolean = false>(
  options: Options<CidadeFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CidadeFindByIdResponses,
    CidadeFindByIdErrors,
    ThrowOnError
  >({ url: '/base/cidades/{id}', ...options });

/**
 * Lista ambientes disponiveis
 *
 * Lista ambientes disponiveis
 */
export const ambienteListDisponiveis = <ThrowOnError extends boolean = false>(
  options?: Options<AmbienteListDisponiveisData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AmbienteListDisponiveisResponses,
    AmbienteListDisponiveisErrors,
    ThrowOnError
  >({ url: '/ambientes/disponiveis', ...options });

/**
 * Lista ambientes
 *
 * Lista ambientes
 */
export const ambienteFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<AmbienteFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AmbienteFindAllResponses,
    AmbienteFindAllErrors,
    ThrowOnError
  >({ url: '/ambientes', ...options });

/**
 * Cria um ambiente
 *
 * Cria um ambiente
 */
export const ambienteCreate = <ThrowOnError extends boolean = false>(
  options: Options<AmbienteCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AmbienteCreateResponses,
    AmbienteCreateErrors,
    ThrowOnError
  >({
    url: '/ambientes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Grade de disponibilidade de um ambiente
 *
 * Grade de disponibilidade de um ambiente
 */
export const ambienteGetDisponibilidade = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AmbienteGetDisponibilidadeData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AmbienteGetDisponibilidadeResponses,
    AmbienteGetDisponibilidadeErrors,
    ThrowOnError
  >({ url: '/ambientes/{id}/disponibilidade', ...options });

/**
 * Remove um ambiente
 *
 * Remove um ambiente
 */
export const ambienteDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<AmbienteDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    AmbienteDeleteOneByIdResponses,
    AmbienteDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/ambientes/{id}', ...options });

/**
 * Busca um ambiente por ID
 *
 * Busca um ambiente por ID
 */
export const ambienteFindById = <ThrowOnError extends boolean = false>(
  options: Options<AmbienteFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AmbienteFindByIdResponses,
    AmbienteFindByIdErrors,
    ThrowOnError
  >({ url: '/ambientes/{id}', ...options });

/**
 * Atualiza um ambiente
 *
 * Atualiza um ambiente
 */
export const ambienteUpdate = <ThrowOnError extends boolean = false>(
  options: Options<AmbienteUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    AmbienteUpdateResponses,
    AmbienteUpdateErrors,
    ThrowOnError
  >({
    url: '/ambientes/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Obtem a imagem de capa de um ambiente
 *
 * Obtem a imagem de capa de um ambiente
 */
export const ambienteGetImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<AmbienteGetImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).get<
    AmbienteGetImagemCapaResponses,
    AmbienteGetImagemCapaErrors,
    ThrowOnError
  >({ url: '/ambientes/{id}/imagem/capa', ...options });

/**
 * Define a imagem de capa de um ambiente
 *
 * Define a imagem de capa de um ambiente
 */
export const ambienteUpdateImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<AmbienteUpdateImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).put<
    AmbienteUpdateImagemCapaResponses,
    AmbienteUpdateImagemCapaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/ambientes/{id}/imagem/capa',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Lista blocos
 *
 * Lista blocos
 */
export const blocoFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<BlocoFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    BlocoFindAllResponses,
    BlocoFindAllErrors,
    ThrowOnError
  >({ url: '/blocos', ...options });

/**
 * Cria um bloco
 *
 * Cria um bloco
 */
export const blocoCreate = <ThrowOnError extends boolean = false>(
  options: Options<BlocoCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    BlocoCreateResponses,
    BlocoCreateErrors,
    ThrowOnError
  >({
    url: '/blocos',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove um bloco
 *
 * Remove um bloco
 */
export const blocoDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<BlocoDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    BlocoDeleteOneByIdResponses,
    BlocoDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/blocos/{id}', ...options });

/**
 * Busca um bloco por ID
 *
 * Busca um bloco por ID
 */
export const blocoFindById = <ThrowOnError extends boolean = false>(
  options: Options<BlocoFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    BlocoFindByIdResponses,
    BlocoFindByIdErrors,
    ThrowOnError
  >({ url: '/blocos/{id}', ...options });

/**
 * Atualiza um bloco
 *
 * Atualiza um bloco
 */
export const blocoUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BlocoUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    BlocoUpdateResponses,
    BlocoUpdateErrors,
    ThrowOnError
  >({
    url: '/blocos/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Obtem a imagem de capa de um bloco
 *
 * Obtem a imagem de capa de um bloco
 */
export const blocoGetImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<BlocoGetImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).get<
    BlocoGetImagemCapaResponses,
    BlocoGetImagemCapaErrors,
    ThrowOnError
  >({ url: '/blocos/{id}/imagem/capa', ...options });

/**
 * Define a imagem de capa de um bloco
 *
 * Define a imagem de capa de um bloco
 */
export const blocoUpdateImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<BlocoUpdateImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).put<
    BlocoUpdateImagemCapaResponses,
    BlocoUpdateImagemCapaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/blocos/{id}/imagem/capa',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Retorna informacoes de ensino do usuario logado
 *
 * Retorna informacoes de ensino do usuario logado
 */
export const autenticacaoWhoAmIEnsino = <ThrowOnError extends boolean = false>(
  options?: Options<AutenticacaoWhoAmIEnsinoData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AutenticacaoWhoAmIEnsinoResponses,
    AutenticacaoWhoAmIEnsinoErrors,
    ThrowOnError
  >({ url: '/autenticacao/quem-sou-eu/ensino', ...options });

/**
 * Retorna informacoes do usuario logado
 *
 * Retorna informacoes do usuario logado
 */
export const autenticacaoWhoAmI = <ThrowOnError extends boolean = false>(
  options?: Options<AutenticacaoWhoAmIData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AutenticacaoWhoAmIResponses,
    AutenticacaoWhoAmIErrors,
    ThrowOnError
  >({ url: '/autenticacao/quem-sou-eu', ...options });

/**
 * Realiza login com matricula e senha
 *
 * Realiza login com matricula e senha
 */
export const autenticacaoLogin = <ThrowOnError extends boolean = false>(
  options: Options<AutenticacaoLoginData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AutenticacaoLoginResponses,
    AutenticacaoLoginErrors,
    ThrowOnError
  >({
    url: '/autenticacao/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Atualiza token de acesso usando refresh token
 *
 * Atualiza token de acesso usando refresh token
 */
export const autenticacaoRefresh = <ThrowOnError extends boolean = false>(
  options: Options<AutenticacaoRefreshData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AutenticacaoRefreshResponses,
    AutenticacaoRefreshErrors,
    ThrowOnError
  >({
    url: '/autenticacao/login/refresh',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Define senha inicial do usuario
 *
 * Define senha inicial do usuario
 */
export const autenticacaoSetInitialPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AutenticacaoSetInitialPasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AutenticacaoSetInitialPasswordResponses,
    AutenticacaoSetInitialPasswordErrors,
    ThrowOnError
  >({
    url: '/autenticacao/definir-senha',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Envia email para redefinir senha
 *
 * Envia email para redefinir senha
 */
export const autenticacaoRequestPasswordReset = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AutenticacaoRequestPasswordResetData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AutenticacaoRequestPasswordResetResponses,
    AutenticacaoRequestPasswordResetErrors,
    ThrowOnError
  >({
    url: '/autenticacao/redefinir-senha',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista diarios
 *
 * Lista diarios
 */
export const diarioFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<DiarioFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    DiarioFindAllResponses,
    DiarioFindAllErrors,
    ThrowOnError
  >({ url: '/diarios', ...options });

/**
 * Cria um diario
 *
 * Cria um diario
 */
export const diarioCreate = <ThrowOnError extends boolean = false>(
  options: Options<DiarioCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    DiarioCreateResponses,
    DiarioCreateErrors,
    ThrowOnError
  >({
    url: '/diarios',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove um diario
 *
 * Remove um diario
 */
export const diarioDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<DiarioDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DiarioDeleteOneByIdResponses,
    DiarioDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/diarios/{id}', ...options });

/**
 * Busca um diario por ID
 *
 * Busca um diario por ID
 */
export const diarioFindById = <ThrowOnError extends boolean = false>(
  options: Options<DiarioFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    DiarioFindByIdResponses,
    DiarioFindByIdErrors,
    ThrowOnError
  >({ url: '/diarios/{id}', ...options });

/**
 * Atualiza um diario
 *
 * Atualiza um diario
 */
export const diarioUpdate = <ThrowOnError extends boolean = false>(
  options: Options<DiarioUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    DiarioUpdateResponses,
    DiarioUpdateErrors,
    ThrowOnError
  >({
    url: '/diarios/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Cria diarios em lote para uma turma
 *
 * Cria diarios em lote para uma turma
 */
export const diarioBatchCreate = <ThrowOnError extends boolean = false>(
  options: Options<DiarioBatchCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    DiarioBatchCreateResponses,
    DiarioBatchCreateErrors,
    ThrowOnError
  >({
    url: '/diarios/batch',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista professores de um diario
 *
 * Lista professores de um diario
 */
export const diarioProfessorFindAll = <ThrowOnError extends boolean = false>(
  options: Options<DiarioProfessorFindAllData, ThrowOnError>
) =>
  (options.client ?? client).get<
    DiarioProfessorFindAllResponses,
    DiarioProfessorFindAllErrors,
    ThrowOnError
  >({ url: '/diarios/{diarioId}/professores', ...options });

/**
 * Substitui professores de um diario
 *
 * Substitui professores de um diario
 */
export const diarioProfessorBulkReplace = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DiarioProfessorBulkReplaceData, ThrowOnError>
) =>
  (options.client ?? client).put<
    DiarioProfessorBulkReplaceResponses,
    DiarioProfessorBulkReplaceErrors,
    ThrowOnError
  >({
    url: '/diarios/{diarioId}/professores',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista preferencias de agrupamento de um diario
 *
 * Lista preferencias de agrupamento de um diario
 */
export const diarioPreferenciaAgrupamentoFindAll = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DiarioPreferenciaAgrupamentoFindAllData, ThrowOnError>
) =>
  (options.client ?? client).get<
    DiarioPreferenciaAgrupamentoFindAllResponses,
    DiarioPreferenciaAgrupamentoFindAllErrors,
    ThrowOnError
  >({ url: '/diarios/{diarioId}/preferencias-agrupamento', ...options });

/**
 * Substitui preferencias de agrupamento de um diario
 *
 * Substitui preferencias de agrupamento de um diario
 */
export const diarioPreferenciaAgrupamentoBulkReplace = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DiarioPreferenciaAgrupamentoBulkReplaceData, ThrowOnError>
) =>
  (options.client ?? client).put<
    DiarioPreferenciaAgrupamentoBulkReplaceResponses,
    DiarioPreferenciaAgrupamentoBulkReplaceErrors,
    ThrowOnError
  >({
    url: '/diarios/{diarioId}/preferencias-agrupamento',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista turmas
 *
 * Lista turmas
 */
export const turmaFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<TurmaFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    TurmaFindAllResponses,
    TurmaFindAllErrors,
    ThrowOnError
  >({ url: '/turmas', ...options });

/**
 * Cria uma turma
 *
 * Cria uma turma
 */
export const turmaCreate = <ThrowOnError extends boolean = false>(
  options: Options<TurmaCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TurmaCreateResponses,
    TurmaCreateErrors,
    ThrowOnError
  >({
    url: '/turmas',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove uma turma
 *
 * Remove uma turma
 */
export const turmaDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<TurmaDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    TurmaDeleteOneByIdResponses,
    TurmaDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/turmas/{id}', ...options });

/**
 * Busca uma turma por ID
 *
 * Busca uma turma por ID
 */
export const turmaFindById = <ThrowOnError extends boolean = false>(
  options: Options<TurmaFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TurmaFindByIdResponses,
    TurmaFindByIdErrors,
    ThrowOnError
  >({ url: '/turmas/{id}', ...options });

/**
 * Atualiza uma turma
 *
 * Atualiza uma turma
 */
export const turmaUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TurmaUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    TurmaUpdateResponses,
    TurmaUpdateErrors,
    ThrowOnError
  >({
    url: '/turmas/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Consulta horario semanal de uma turma
 *
 * Consulta horario semanal de uma turma
 */
export const turmaHorarioSemanal = <ThrowOnError extends boolean = false>(
  options: Options<TurmaHorarioSemanalData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TurmaHorarioSemanalResponses,
    TurmaHorarioSemanalErrors,
    ThrowOnError
  >({ url: '/turmas/{id}/horario', ...options });

/**
 * Busca a imagem de capa de uma turma
 *
 * Busca a imagem de capa de uma turma
 */
export const turmaGetImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<TurmaGetImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TurmaGetImagemCapaResponses,
    TurmaGetImagemCapaErrors,
    ThrowOnError
  >({ url: '/turmas/{id}/imagem/capa', ...options });

/**
 * Define a imagem de capa de uma turma
 *
 * Define a imagem de capa de uma turma
 */
export const turmaUpdateImagemCapa = <ThrowOnError extends boolean = false>(
  options: Options<TurmaUpdateImagemCapaData, ThrowOnError>
) =>
  (options.client ?? client).put<
    TurmaUpdateImagemCapaResponses,
    TurmaUpdateImagemCapaErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/turmas/{id}/imagem/capa',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Lista eventos da turma
 */
export const turmaEventoFindAll = <ThrowOnError extends boolean = false>(
  options: Options<TurmaEventoFindAllData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TurmaEventoFindAllResponses,
    TurmaEventoFindAllErrors,
    ThrowOnError
  >({ url: '/turmas/{turmaId}/eventos', ...options });

/**
 * Cria evento escopado a turma
 */
export const turmaEventoCreate = <ThrowOnError extends boolean = false>(
  options: Options<TurmaEventoCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TurmaEventoCreateResponses,
    TurmaEventoCreateErrors,
    ThrowOnError
  >({
    url: '/turmas/{turmaId}/eventos',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove evento da turma
 */
export const turmaEventoDelete = <ThrowOnError extends boolean = false>(
  options: Options<TurmaEventoDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    TurmaEventoDeleteResponses,
    TurmaEventoDeleteErrors,
    ThrowOnError
  >({ url: '/turmas/{turmaId}/eventos/{eventoId}', ...options });

/**
 * Atualiza evento da turma
 */
export const turmaEventoUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TurmaEventoUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    TurmaEventoUpdateResponses,
    TurmaEventoUpdateErrors,
    ThrowOnError
  >({
    url: '/turmas/{turmaId}/eventos/{eventoId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Configura diarios da turma em lote (disciplinas + professores)
 */
export const turmaDiarioConfigurar = <ThrowOnError extends boolean = false>(
  options: Options<TurmaDiarioConfigurarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TurmaDiarioConfigurarResponses,
    TurmaDiarioConfigurarErrors,
    ThrowOnError
  >({
    url: '/turmas/{turmaId}/diarios/configurar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Solicita geracao de horario (assincrono)
 *
 * Solicita geracao de horario (assincrono)
 */
export const gerarHorarioCreate = <ThrowOnError extends boolean = false>(
  options: Options<GerarHorarioCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    GerarHorarioCreateResponses,
    GerarHorarioCreateErrors,
    ThrowOnError
  >({
    url: '/gerar-horario',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Consulta status de uma geracao de horario
 *
 * Consulta status de uma geracao de horario
 */
export const gerarHorarioFindById = <ThrowOnError extends boolean = false>(
  options: Options<GerarHorarioFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GerarHorarioFindByIdResponses,
    GerarHorarioFindByIdErrors,
    ThrowOnError
  >({ url: '/gerar-horario/{id}', ...options });

/**
 * Aceita o horario gerado e aplica ao calendario
 *
 * Aceita o horario gerado e aplica ao calendario
 */
export const gerarHorarioAceitar = <ThrowOnError extends boolean = false>(
  options: Options<GerarHorarioAceitarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    GerarHorarioAceitarResponses,
    GerarHorarioAceitarErrors,
    ThrowOnError
  >({ url: '/gerar-horario/{id}/aceitar', ...options });

/**
 * Rejeita o horario gerado
 *
 * Rejeita o horario gerado
 */
export const gerarHorarioRejeitar = <ThrowOnError extends boolean = false>(
  options: Options<GerarHorarioRejeitarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    GerarHorarioRejeitarResponses,
    GerarHorarioRejeitarErrors,
    ThrowOnError
  >({ url: '/gerar-horario/{id}/rejeitar', ...options });

/**
 * Cria nova sessao de edicao de horario
 *
 * Cria nova sessao de edicao de horario
 */
export const horarioEdicaoCreate = <ThrowOnError extends boolean = false>(
  options?: Options<HorarioEdicaoCreateData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    HorarioEdicaoCreateResponses,
    HorarioEdicaoCreateErrors,
    ThrowOnError
  >({ url: '/horarios/edicao', ...options });

/**
 * Aplica uma mudanca a sessao de edicao de horario
 *
 * Aplica uma mudanca a sessao de edicao de horario
 */
export const horarioEdicaoApplyChange = <ThrowOnError extends boolean = false>(
  options: Options<HorarioEdicaoApplyChangeData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    HorarioEdicaoApplyChangeResponses,
    HorarioEdicaoApplyChangeErrors,
    ThrowOnError
  >({
    url: '/horarios/edicao/{sessaoId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Salva sessao de edicao permanentemente
 *
 * Salva sessao de edicao permanentemente
 */
export const horarioEdicaoSalvar = <ThrowOnError extends boolean = false>(
  options: Options<HorarioEdicaoSalvarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    HorarioEdicaoSalvarResponses,
    HorarioEdicaoSalvarErrors,
    ThrowOnError
  >({ url: '/horarios/edicao/{sessaoId}/salvar', ...options });

/**
 * Cancela e descarta sessao de edicao
 *
 * Cancela e descarta sessao de edicao
 */
export const horarioEdicaoCancelar = <ThrowOnError extends boolean = false>(
  options: Options<HorarioEdicaoCancelarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    HorarioEdicaoCancelarResponses,
    HorarioEdicaoCancelarErrors,
    ThrowOnError
  >({ url: '/horarios/edicao/{sessaoId}/cancelar', ...options });

/**
 * Lista estados
 *
 * Lista estados
 */
export const estadoFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<EstadoFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    EstadoFindAllResponses,
    EstadoFindAllErrors,
    ThrowOnError
  >({ url: '/base/estados', ...options });

/**
 * Busca um estado por ID
 *
 * Busca um estado por ID
 */
export const estadoFindById = <ThrowOnError extends boolean = false>(
  options: Options<EstadoFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    EstadoFindByIdResponses,
    EstadoFindByIdErrors,
    ThrowOnError
  >({ url: '/base/estados/{id}', ...options });

/**
 * Lista empresas
 *
 * Lista empresas
 */
export const empresaFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<EmpresaFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    EmpresaFindAllResponses,
    EmpresaFindAllErrors,
    ThrowOnError
  >({ url: '/empresas', ...options });

/**
 * Cria uma empresa
 *
 * Cria uma empresa
 */
export const empresaCreate = <ThrowOnError extends boolean = false>(
  options: Options<EmpresaCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    EmpresaCreateResponses,
    EmpresaCreateErrors,
    ThrowOnError
  >({
    url: '/empresas',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Deleta uma empresa
 *
 * Deleta uma empresa
 */
export const empresaDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<EmpresaDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    EmpresaDeleteOneByIdResponses,
    EmpresaDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/empresas/{id}', ...options });

/**
 * Busca uma empresa por ID
 *
 * Busca uma empresa por ID
 */
export const empresaFindById = <ThrowOnError extends boolean = false>(
  options: Options<EmpresaFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    EmpresaFindByIdResponses,
    EmpresaFindByIdErrors,
    ThrowOnError
  >({ url: '/empresas/{id}', ...options });

/**
 * Atualiza uma empresa
 *
 * Atualiza uma empresa
 */
export const empresaUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EmpresaUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    EmpresaUpdateResponses,
    EmpresaUpdateErrors,
    ThrowOnError
  >({
    url: '/empresas/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista estágios
 *
 * Lista estágios
 */
export const estagioFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<EstagioFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    EstagioFindAllResponses,
    EstagioFindAllErrors,
    ThrowOnError
  >({ url: '/estagios', ...options });

/**
 * Cria um estágio
 *
 * Cria um estágio
 */
export const estagioCreate = <ThrowOnError extends boolean = false>(
  options: Options<EstagioCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    EstagioCreateResponses,
    EstagioCreateErrors,
    ThrowOnError
  >({
    url: '/estagios',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Deleta um estágio
 *
 * Deleta um estágio
 */
export const estagioDelete = <ThrowOnError extends boolean = false>(
  options: Options<EstagioDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    EstagioDeleteResponses,
    EstagioDeleteErrors,
    ThrowOnError
  >({ url: '/estagios/{id}', ...options });

/**
 * Busca um estágio por ID
 *
 * Busca um estágio por ID
 */
export const estagioFindById = <ThrowOnError extends boolean = false>(
  options: Options<EstagioFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    EstagioFindByIdResponses,
    EstagioFindByIdErrors,
    ThrowOnError
  >({ url: '/estagios/{id}', ...options });

/**
 * Atualiza um estágio
 *
 * Atualiza um estágio
 */
export const estagioUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EstagioUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    EstagioUpdateResponses,
    EstagioUpdateErrors,
    ThrowOnError
  >({
    url: '/estagios/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista estagiários
 *
 * Lista estagiários
 */
export const estagiarioFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<EstagiarioFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    EstagiarioFindAllResponses,
    EstagiarioFindAllErrors,
    ThrowOnError
  >({ url: '/estagiarios', ...options });

/**
 * Cria um estagiário
 *
 * Cria um estagiário
 */
export const estagiarioCreate = <ThrowOnError extends boolean = false>(
  options: Options<EstagiarioCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    EstagiarioCreateResponses,
    EstagiarioCreateErrors,
    ThrowOnError
  >({
    url: '/estagiarios',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Deleta um estagiário
 *
 * Deleta um estagiário
 */
export const estagiarioDeleteOneById = <ThrowOnError extends boolean = false>(
  options: Options<EstagiarioDeleteOneByIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    EstagiarioDeleteOneByIdResponses,
    EstagiarioDeleteOneByIdErrors,
    ThrowOnError
  >({ url: '/estagiarios/{id}', ...options });

/**
 * Busca um estagiário por ID
 *
 * Busca um estagiário por ID
 */
export const estagiarioFindById = <ThrowOnError extends boolean = false>(
  options: Options<EstagiarioFindByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    EstagiarioFindByIdResponses,
    EstagiarioFindByIdErrors,
    ThrowOnError
  >({ url: '/estagiarios/{id}', ...options });

/**
 * Atualiza um estagiário
 *
 * Atualiza um estagiário
 */
export const estagiarioUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EstagiarioUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    EstagiarioUpdateResponses,
    EstagiarioUpdateErrors,
    ThrowOnError
  >({
    url: '/estagiarios/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista notificacoes do usuario autenticado
 *
 * Lista notificacoes do usuario autenticado
 */
export const notificacaoFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<NotificacaoFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    NotificacaoFindAllResponses,
    NotificacaoFindAllErrors,
    ThrowOnError
  >({ url: '/notificacoes', ...options });

/**
 * Conta notificacoes nao lidas
 *
 * Conta notificacoes nao lidas
 */
export const notificacaoContagemNaoLidas = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<NotificacaoContagemNaoLidasData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    NotificacaoContagemNaoLidasResponses,
    NotificacaoContagemNaoLidasErrors,
    ThrowOnError
  >({ url: '/notificacoes/contagem-nao-lidas', ...options });

/**
 * Marca notificacao como lida
 *
 * Marca notificacao como lida
 */
export const notificacaoMarcarLida = <ThrowOnError extends boolean = false>(
  options: Options<NotificacaoMarcarLidaData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    NotificacaoMarcarLidaResponses,
    NotificacaoMarcarLidaErrors,
    ThrowOnError
  >({ url: '/notificacoes/{id}/lida', ...options });

/**
 * Relatorio de aulas ministradas (JSON)
 */
export const relatorioAulasMinistradas = <ThrowOnError extends boolean = false>(
  options: Options<RelatorioAulasMinistradasData, ThrowOnError>
) =>
  (options.client ?? client).get<
    RelatorioAulasMinistradasResponses,
    RelatorioAulasMinistradasErrors,
    ThrowOnError
  >({ url: '/relatorios/aulas-ministradas', ...options });

/**
 * Relatorio de aulas ministradas (PDF)
 */
export const relatorioAulasMinistradasPdf = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RelatorioAulasMinistradasPdfData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    unknown,
    RelatorioAulasMinistradasPdfErrors,
    ThrowOnError
  >({ url: '/relatorios/aulas-ministradas/pdf', ...options });

/**
 * Retorna as grades horarias ativas de um campus
 *
 * Retorna as grades horarias ativas de um campus
 */
export const gradeHorariaFindByCampus = <ThrowOnError extends boolean = false>(
  options: Options<GradeHorariaFindByCampusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GradeHorariaFindByCampusResponses,
    GradeHorariaFindByCampusErrors,
    ThrowOnError
  >({ url: '/grades-horarias/{campusId}', ...options });

/**
 * Substitui as grades horarias de um campus (estado completo)
 *
 * Substitui as grades horarias de um campus (estado completo)
 */
export const gradeHorariaReplace = <ThrowOnError extends boolean = false>(
  options: Options<GradeHorariaReplaceData, ThrowOnError>
) =>
  (options.client ?? client).put<
    GradeHorariaReplaceResponses,
    GradeHorariaReplaceErrors,
    ThrowOnError
  >({
    url: '/grades-horarias/{campusId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Lista todas as configuracoes ativas de disponibilidade da turma
 *
 * Lista todas as configuracoes ativas de disponibilidade da turma
 */
export const turmaDisponibilidadeFindAllActive = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TurmaDisponibilidadeFindAllActiveData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TurmaDisponibilidadeFindAllActiveResponses,
    TurmaDisponibilidadeFindAllActiveErrors,
    ThrowOnError
  >({ url: '/horarios/turmas/{id}/disponibilidade/all', ...options });

/**
 * Consulta disponibilidade da turma para uma semana
 *
 * Consulta disponibilidade da turma para uma semana
 */
export const turmaDisponibilidadeFindByWeek = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TurmaDisponibilidadeFindByWeekData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TurmaDisponibilidadeFindByWeekResponses,
    TurmaDisponibilidadeFindByWeekErrors,
    ThrowOnError
  >({ url: '/horarios/turmas/{id}/disponibilidade', ...options });

/**
 * Define disponibilidade da turma
 *
 * Define disponibilidade da turma
 */
export const turmaDisponibilidadeSave = <ThrowOnError extends boolean = false>(
  options: Options<TurmaDisponibilidadeSaveData, ThrowOnError>
) =>
  (options.client ?? client).put<
    TurmaDisponibilidadeSaveResponses,
    TurmaDisponibilidadeSaveErrors,
    ThrowOnError
  >({
    url: '/horarios/turmas/{id}/disponibilidade',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Desativa uma configuracao de disponibilidade da turma
 *
 * Desativa uma configuracao de disponibilidade da turma
 */
export const turmaDisponibilidadeDeactivate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TurmaDisponibilidadeDeactivateData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    TurmaDisponibilidadeDeactivateResponses,
    TurmaDisponibilidadeDeactivateErrors,
    ThrowOnError
  >({ url: '/horarios/turmas/{id}/disponibilidade/{configId}', ...options });
