apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
  namespace: ladesa
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: web-service
      port: 80
      targetPort: web-port
