apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ladesa-ro-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: ladesa-ro-issuer-production
  namespace: ladesa-ro-development
spec:
  tls:
    - hosts:
        - dev.ladesa.com.br
      secretName: ladesa-ro-development-web-tls
  rules:
    - host: dev.ladesa.com.br
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ladesa-ro-web
                port:
                  name: web-service