export type {
  ScheduleDiscipline as IGradeDisciplina,
  ScheduleShiftModel as ITurno,
  ScheduleShiftSlot as ITurnoHorario,
  ScheduleShiftSlots as ITurnoHorarios,
  ScheduleShiftsModel as ITurnos,
  ScheduleWeekDay as IDiaDaSemana,
  ScheduleWeekDays as IDiasDaSemana,
} from '@ladesa-ro/web.ui';
