// This file is auto-generated by @hey-api/openapi-ts

export type PaginationMetaRestDto = {
  /**
   * Quantidade de itens por pagina
   */
  itemsPerPage: number;
  /**
   * Total de itens
   */
  totalItems: number;
  /**
   * Pagina atual
   */
  currentPage: number;
  /**
   * Quantidade total de paginas
   */
  totalPages: number;
  /**
   * Termo textual da busca
   */
  search: string;
  /**
   * Ordenacao aplicada
   */
  sortBy: Array<[string, string]>;
  /**
   * Filtros aplicados
   */
  filter?: {
    [key: string]: unknown;
  };
};

export type ModalidadeFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome da modalidade
   */
  nome: string;
  /**
   * Apelido da modalidade
   */
  slug: string;
};

export type ModalidadeListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<ModalidadeFindOneOutputDto>;
};

export type ModalidadeCreateInputDto = {
  /**
   * Nome da modalidade
   */
  nome: string;
  /**
   * Apelido da modalidade
   */
  slug: string;
};

export type ModalidadeUpdateInputDto = {
  /**
   * Nome da modalidade
   */
  nome?: string;
  /**
   * Apelido da modalidade
   */
  slug?: string;
};

export type EstadoFindOneOutputDto = {
  /**
   * Identificador do registro (numerico)
   */
  id: number;
  /**
   * Nome oficial do estado
   */
  nome: string;
  /**
   * Sigla do estado
   */
  sigla: string;
};

export type CidadeFindOneOutputDto = {
  /**
   * Identificador do registro (numerico)
   */
  id: number;
  /**
   * Nome oficial da cidade
   */
  nome: string;
  /**
   * Estado da cidade
   */
  estado: EstadoFindOneOutputDto;
};

export type EnderecoFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Codigo postal (CEP)
   */
  cep: string;
  /**
   * Logradouro
   */
  logradouro: string;
  /**
   * Numero
   */
  numero: number;
  /**
   * Bairro
   */
  bairro: string;
  /**
   * Complemento
   */
  complemento?: string | null;
  /**
   * Ponto de referencia
   */
  pontoReferencia?: string | null;
  /**
   * Cidade
   */
  cidade: CidadeFindOneOutputDto;
};

export type CampusFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome fantasia do campus
   */
  nomeFantasia: string;
  /**
   * Razao social do campus
   */
  razaoSocial: string;
  /**
   * Apelido do campus
   */
  apelido: string;
  /**
   * CNPJ do campus
   */
  cnpj: string;
  /**
   * Endereco do campus
   */
  endereco: EnderecoFindOneOutputDto;
};

export type ArquivoFindOneOutputFromBlocoDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type ImagemArquivoFindOneFromImagemOutputFromBlocoDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Largura da imagem
   */
  largura: number;
  /**
   * Altura da imagem
   */
  altura: number;
  /**
   * Formato da imagem
   */
  formato: string;
  /**
   * Mime-type da imagem
   */
  mimeType: string;
  /**
   * Arquivo
   */
  arquivo: ArquivoFindOneOutputFromBlocoDto;
};

export type ImagemFindOneOutputFromBlocoDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Descricao da imagem
   */
  descricao?: string | null;
  /**
   * Versoes da imagem
   */
  versoes: Array<ImagemArquivoFindOneFromImagemOutputFromBlocoDto>;
};

export type UsuarioFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome do usuario
   */
  nome?: string | null;
  /**
   * Matrícula do usuário
   */
  matricula?: string | null;
  /**
   * E-mail do usuario
   */
  email?: string | null;
  /**
   * Diz que o usuario tem poderes de administrador
   */
  isSuperUser: boolean;
  /**
   * Imagem de capa do usuario
   */
  imagemCapa?: ImagemFindOneOutputFromBlocoDto | null;
  /**
   * Imagem de perfil do usuario
   */
  imagemPerfil?: ImagemFindOneOutputFromBlocoDto | null;
};

export type PerfilFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Indica se o vinculo esta ativo
   */
  ativo: boolean;
  /**
   * Cargo do usuario no vinculo
   */
  cargo: string;
  /**
   * Campus associado ao vinculo
   */
  campus: CampusFindOneOutputDto;
  /**
   * Usuario associado ao vinculo
   */
  usuario: UsuarioFindOneOutputDto;
};

export type PerfilListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<PerfilFindOneOutputDto>;
};

export type CampusFindOneInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioFindOneInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type PerfilSetVinculosInputDto = {
  /**
   * Lista de cargos que o usuario tera no campus
   */
  cargos: Array<string>;
  /**
   * Campus associado ao vinculo
   */
  campus: CampusFindOneInputDto;
  /**
   * Usuario associado ao vinculo
   */
  usuario: UsuarioFindOneInputDto;
};

export type UsuarioListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<UsuarioFindOneOutputDto>;
};

export type UsuarioEnsinoTurmaRefDto = {
  /**
   * ID da turma
   */
  id: string;
  /**
   * Periodo da turma
   */
  periodo: string;
};

export type UsuarioEnsinoCursoRefDto = {
  /**
   * ID do curso
   */
  id: string;
  /**
   * Nome do curso
   */
  nome: string;
  /**
   * Turmas do curso onde o usuario leciona
   */
  turmas: Array<UsuarioEnsinoTurmaRefDto>;
};

export type UsuarioEnsinoDisciplinaRefDto = {
  /**
   * ID da disciplina
   */
  id: string;
  /**
   * Nome da disciplina
   */
  nome: string;
  /**
   * Cursos onde o usuario leciona esta disciplina
   */
  cursos: Array<UsuarioEnsinoCursoRefDto>;
};

export type UsuarioEnsinoOutputDto = {
  /**
   * Dados do usuario
   */
  usuario: UsuarioFindOneOutputDto;
  /**
   * Disciplinas onde o usuario leciona (com cursos e turmas)
   */
  disciplinas: Array<UsuarioEnsinoDisciplinaRefDto>;
};

export type UsuarioCreateInputDto = {
  /**
   * Nome do usuario
   */
  nome?: string | null;
  /**
   * Matrícula do usuário
   */
  matricula?: string | null;
  /**
   * E-mail do usuario
   */
  email?: string | null;
};

export type UsuarioUpdateInputDto = {
  /**
   * Nome do usuario
   */
  nome?: string | null;
  /**
   * Matrícula do usuário
   */
  matricula?: string | null;
  /**
   * E-mail do usuario
   */
  email?: string | null;
};

export type HorarioAulaItemDisciplinaDto = {
  id: string;
  nome: string;
  nomeAbreviado: string;
};

export type HorarioAulaItemTurmaDto = {
  id: string;
  periodo: number;
};

export type HorarioAulaItemDiarioDto = {
  id: string;
  disciplina: HorarioAulaItemDisciplinaDto;
  turma: HorarioAulaItemTurmaDto;
};

export type HorarioAulaItemProfessorPerfilDto = {
  id: string;
  cargo: string;
};

export type HorarioAulaItemProfessorUsuarioDto = {
  id: string;
  nome?: string | null;
};

export type HorarioAulaItemProfessorDto = {
  id: string;
  perfil: HorarioAulaItemProfessorPerfilDto;
  usuario: HorarioAulaItemProfessorUsuarioDto;
};

export type HorarioAulaItemAmbienteDto = {
  id: string;
  nome: string;
  codigo: string;
};

export type HorarioAulaItemDto = {
  id: string;
  dataInicio: string;
  dataFim?: string | null;
  horarioInicio: string;
  horarioFim: string;
  nome?: string | null;
  cor?: string | null;
  diario?: HorarioAulaItemDiarioDto | null;
  professores: Array<HorarioAulaItemProfessorDto>;
  ambiente?: HorarioAulaItemAmbienteDto | null;
};

export type HorarioSemanalDiaDto = {
  data: string;
  /**
   * 0=dom, 1=seg, ..., 6=sab
   */
  diaSemana: number;
  aulas: Array<HorarioAulaItemDto>;
};

export type HorarioSemanalOutputDto = {
  semanaInicio: string;
  semanaFim: string;
  dias: Array<HorarioSemanalDiaDto>;
};

export type UsuarioEventoFindOneOutputDto = {
  id: string;
  nome?: string | null;
  tipo: string;
  dataInicio: string;
  dataFim?: string | null;
  diaInteiro: boolean;
  horarioInicio: string;
  horarioFim: string;
  cor?: string | null;
  repeticao?: string | null;
  status?: string | null;
};

export type UsuarioEventoListOutputDto = {
  data: Array<UsuarioEventoFindOneOutputDto>;
};

export type UsuarioEventoCreateInputDto = {
  /**
   * Nome do evento/atividade
   */
  nome: string;
  dataInicio: string;
  dataFim?: string | null;
  diaInteiro: boolean;
  horarioInicio?: string;
  horarioFim?: string;
  cor?: string | null;
  repeticao?: string | null;
  /**
   * Tipo: EVENTO (atividade) ou INDISPONIBILIDADE
   */
  tipo?: 'EVENTO' | 'INDISPONIBILIDADE';
};

/**
 * Tipo: EVENTO (atividade) ou INDISPONIBILIDADE
 */
export type tipo = 'EVENTO' | 'INDISPONIBILIDADE';

export type UsuarioEventoUpdateInputDto = {
  nome?: string;
  dataInicio?: string;
  dataFim?: string | null;
  diaInteiro?: boolean;
  horarioInicio?: string;
  horarioFim?: string;
  cor?: string | null;
  repeticao?: string | null;
};

export type CampusListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<CampusFindOneOutputDto>;
};

export type CidadeFindOneInputDto = {
  /**
   * Identificador do registro (numerico)
   */
  id: number;
};

export type EnderecoInputDto = {
  /**
   * Codigo postal (CEP)
   */
  cep: string;
  /**
   * Logradouro
   */
  logradouro: string;
  /**
   * Numero
   */
  numero: number;
  /**
   * Bairro
   */
  bairro: string;
  /**
   * Complemento
   */
  complemento?: string | null;
  /**
   * Ponto de referencia
   */
  pontoReferencia?: string | null;
  /**
   * Cidade
   */
  cidade: CidadeFindOneInputDto;
};

export type CampusCreateInputDto = {
  /**
   * Nome fantasia do campus
   */
  nomeFantasia: string;
  /**
   * Razao social do campus
   */
  razaoSocial: string;
  /**
   * Apelido do campus
   */
  apelido: string;
  /**
   * CNPJ do campus
   */
  cnpj: string;
  /**
   * Endereco do campus
   */
  endereco: EnderecoInputDto;
};

export type CampusUpdateInputDto = {
  /**
   * Nome fantasia do campus
   */
  nomeFantasia?: string;
  /**
   * Razao social do campus
   */
  razaoSocial?: string;
  /**
   * Apelido do campus
   */
  apelido?: string;
  /**
   * CNPJ do campus
   */
  cnpj?: string;
  /**
   * Endereco do campus
   */
  endereco?: EnderecoInputDto;
};

export type NivelFormacaoFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Apelido do nivel de formacao
   */
  slug: string;
};

export type OfertaFormacaoPeriodoEtapaOutputDto = {
  id: string;
  nome: string;
  cor: string;
};

export type OfertaFormacaoPeriodoOutputDto = {
  id: string;
  numeroPeriodo: number;
  etapas: Array<OfertaFormacaoPeriodoEtapaOutputDto>;
};

export type OfertaFormacaoFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome da oferta de formacao
   */
  nome: string;
  /**
   * Apelido da oferta de formacao
   */
  slug: string;
  /**
   * Duracao de cada periodo em meses
   */
  duracaoPeriodoEmMeses: number;
  /**
   * Modalidade da oferta de formacao
   */
  modalidade: ModalidadeFindOneOutputDto;
  /**
   * Campus da oferta de formacao
   */
  campus: CampusFindOneOutputDto;
  /**
   * Niveis de formacao vinculados a oferta de formacao
   */
  niveisFormacoes: Array<NivelFormacaoFindOneOutputDto>;
  /**
   * Periodos com suas etapas do ano letivo
   */
  periodos: Array<OfertaFormacaoPeriodoOutputDto>;
};

export type CursoFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome do curso
   */
  nome: string;
  /**
   * Nome abreviado do curso
   */
  nomeAbreviado: string;
  /**
   * Campus que o curso pertence
   */
  campus: CampusFindOneOutputDto;
  /**
   * Oferta de formacao do curso
   */
  ofertaFormacao: OfertaFormacaoFindOneOutputDto;
  /**
   * Imagem de capa do curso
   */
  imagemCapa?: ImagemFindOneOutputFromBlocoDto | null;
};

export type CursoListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<CursoFindOneOutputDto>;
};

export type CursoCreateInputDto = {
  /**
   * Nome do curso
   */
  nome: string;
  /**
   * Nome abreviado do curso
   */
  nomeAbreviado: string;
  /**
   * Campus que o curso pertence
   */
  campus: {
    [key: string]: unknown;
  };
  /**
   * Oferta de formacao do curso
   */
  ofertaFormacao: {
    [key: string]: unknown;
  };
};

export type CursoUpdateInputDto = {
  /**
   * Nome do curso
   */
  nome?: string;
  /**
   * Nome abreviado do curso
   */
  nomeAbreviado?: string;
  /**
   * Campus que o curso pertence
   */
  campus?: {
    [key: string]: unknown;
  };
  /**
   * Oferta de formacao do curso
   */
  ofertaFormacao?: {
    [key: string]: unknown;
  };
};

export type CursoPeriodoDisciplinaOutputItemDto = {
  id: string;
  disciplinaId: string;
  disciplinaNome?: string | null;
  cargaHoraria?: number | null;
};

export type CursoPeriodoDisciplinaOutputPeriodoDto = {
  numeroPeriodo: number;
  disciplinas: Array<CursoPeriodoDisciplinaOutputItemDto>;
};

export type CursoPeriodoDisciplinaListOutputDto = {
  data: Array<CursoPeriodoDisciplinaOutputPeriodoDto>;
};

export type CursoPeriodoDisciplinaItemDto = {
  /**
   * ID da disciplina
   */
  disciplinaId: string;
  /**
   * Carga horaria
   */
  cargaHoraria?: number;
};

export type CursoPeriodoDisciplinaPeriodoItemDto = {
  /**
   * Numero do periodo
   */
  numeroPeriodo: number;
  /**
   * Disciplinas do periodo
   */
  disciplinas: Array<CursoPeriodoDisciplinaItemDto>;
};

export type CursoPeriodoDisciplinaBulkReplaceInputDto = {
  periodos: Array<CursoPeriodoDisciplinaPeriodoItemDto>;
};

export type OfertaFormacaoListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<OfertaFormacaoFindOneOutputDto>;
};

export type OfertaFormacaoPeriodoEtapaInputDto = {
  /**
   * Nome da etapa
   */
  nome: string;
  /**
   * Cor da etapa (hex)
   */
  cor: string;
};

export type OfertaFormacaoPeriodoInputDto = {
  /**
   * Numero do periodo
   */
  numeroPeriodo: number;
  /**
   * Etapas do periodo (ao menos 1)
   */
  etapas: Array<OfertaFormacaoPeriodoEtapaInputDto>;
};

export type OfertaFormacaoCreateInputDto = {
  /**
   * Nome da oferta de formacao
   */
  nome: string;
  /**
   * Apelido da oferta de formacao
   */
  slug: string;
  /**
   * Duracao de cada periodo em meses
   */
  duracaoPeriodoEmMeses: number;
  /**
   * Modalidade da oferta de formacao
   */
  modalidade: {
    id?: string;
  };
  /**
   * Campus da oferta de formacao
   */
  campus: {
    id?: string;
  };
  /**
   * Niveis de formacao vinculados a oferta de formacao
   */
  niveisFormacoes: Array<{
    id?: string;
  }>;
  /**
   * Periodos com suas etapas do ano letivo
   */
  periodos: Array<OfertaFormacaoPeriodoInputDto>;
};

export type OfertaFormacaoUpdateInputDto = {
  /**
   * Nome da oferta de formacao
   */
  nome?: string;
  /**
   * Apelido da oferta de formacao
   */
  slug?: string;
  /**
   * Duracao de cada periodo em meses
   */
  duracaoPeriodoEmMeses?: number;
  /**
   * Modalidade da oferta de formacao
   */
  modalidade?: {
    id?: string;
  };
  /**
   * Campus da oferta de formacao
   */
  campus?: {
    id?: string;
  };
  /**
   * Niveis de formacao vinculados a oferta de formacao
   */
  niveisFormacoes?: Array<{
    id?: string;
  }>;
  /**
   * Periodos com suas etapas do ano letivo
   */
  periodos?: Array<OfertaFormacaoPeriodoInputDto>;
};

export type NivelFormacaoListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<NivelFormacaoFindOneOutputDto>;
};

export type NivelFormacaoCreateInputDto = {
  /**
   * Apelido do nivel de formacao
   */
  slug: string;
};

export type NivelFormacaoUpdateInputDto = {
  /**
   * Apelido do nivel de formacao
   */
  slug?: string;
};

export type DisciplinaFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome da disciplina
   */
  nome: string;
  /**
   * Nome abreviado da disciplina
   */
  nomeAbreviado: string;
  /**
   * Carga horaria da disciplina
   */
  cargaHoraria: number;
  /**
   * Imagem de capa da disciplina
   */
  imagemCapa?: ImagemFindOneOutputFromBlocoDto | null;
};

export type DisciplinaListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<DisciplinaFindOneOutputDto>;
};

export type DisciplinaCreateInputDto = {
  /**
   * Nome da disciplina
   */
  nome: string;
  /**
   * Nome abreviado da disciplina
   */
  nomeAbreviado: string;
  /**
   * Carga horaria da disciplina
   */
  cargaHoraria: number;
};

export type DisciplinaUpdateInputDto = {
  /**
   * Nome da disciplina
   */
  nome?: string;
  /**
   * Nome abreviado da disciplina
   */
  nomeAbreviado?: string;
  /**
   * Carga horaria da disciplina
   */
  cargaHoraria?: number;
};

export type CalendarioEventoFindOneOutputDto = {
  id: string;
  nome?: string | null;
  dataInicio: string;
  dataFim?: string | null;
  diaInteiro: boolean;
  horarioInicio: string;
  horarioFim: string;
  cor?: string | null;
  repeticao?: string | null;
  status?: string | null;
  turmaIds?: Array<string>;
  perfilIds?: Array<string>;
  calendarioLetivoIds?: Array<string>;
  ofertaFormacaoIds?: Array<string>;
  modalidadeIds?: Array<string>;
};

export type CalendarioEventoListOutputDto = {
  data: Array<CalendarioEventoFindOneOutputDto>;
};

export type CalendarioEventoCreateInputDto = {
  /**
   * Nome do evento
   */
  nome: string;
  /**
   * Data inicio
   */
  dataInicio: string;
  /**
   * Data fim
   */
  dataFim?: string | null;
  /**
   * Evento ocupa o dia inteiro
   */
  diaInteiro: boolean;
  /**
   * Horario inicio (HH:MM)
   */
  horarioInicio?: string;
  /**
   * Horario fim (HH:MM)
   */
  horarioFim?: string;
  /**
   * Cor do evento para exibicao
   */
  cor?: string | null;
  /**
   * Regra de repeticao (iCalendar RRULE)
   */
  repeticao?: string | null;
  /**
   * IDs das turmas participantes
   */
  turmaIds?: Array<string>;
  /**
   * IDs dos perfis (professores) participantes
   */
  perfilIds?: Array<string>;
  /**
   * IDs dos calendarios letivos vinculados
   */
  calendarioLetivoIds?: Array<string>;
  /**
   * IDs das ofertas de formacao vinculadas
   */
  ofertaFormacaoIds?: Array<string>;
  /**
   * IDs das modalidades vinculadas
   */
  modalidadeIds?: Array<string>;
};

export type CalendarioEventoUpdateInputDto = {
  nome?: string;
  dataInicio?: string;
  dataFim?: string | null;
  diaInteiro?: boolean;
  horarioInicio?: string;
  horarioFim?: string;
  cor?: string | null;
  repeticao?: string | null;
  /**
   * IDs das turmas participantes
   */
  turmaIds?: Array<string>;
  /**
   * IDs dos perfis (professores) participantes
   */
  perfilIds?: Array<string>;
  /**
   * IDs dos calendarios letivos vinculados
   */
  calendarioLetivoIds?: Array<string>;
  /**
   * IDs das ofertas de formacao vinculadas
   */
  ofertaFormacaoIds?: Array<string>;
  /**
   * IDs das modalidades vinculadas
   */
  modalidadeIds?: Array<string>;
};

export type CalendarioLetivoFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome do calendario letivo
   */
  nome: string;
  /**
   * Ano do calendario letivo
   */
  ano: number;
  /**
   * Campus ao qual o calendario letivo pertence
   */
  campus: CampusFindOneOutputDto;
  /**
   * Oferta de formacao do calendario letivo
   */
  ofertaFormacao: OfertaFormacaoFindOneOutputDto;
};

export type CalendarioLetivoListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<CalendarioLetivoFindOneOutputDto>;
};

export type OfertaFormacaoFindOneInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CalendarioLetivoCreateInputDto = {
  /**
   * Nome do calendario letivo
   */
  nome: string;
  /**
   * Ano do calendario letivo
   */
  ano: number;
  /**
   * Campus ao qual o calendario letivo pertence
   */
  campus: CampusFindOneInputDto;
  /**
   * Oferta de formacao do calendario letivo
   */
  ofertaFormacao: OfertaFormacaoFindOneInputDto;
};

export type CalendarioLetivoUpdateInputDto = {
  /**
   * Nome do calendario letivo
   */
  nome?: string;
  /**
   * Ano do calendario letivo
   */
  ano?: number;
  /**
   * Campus ao qual o calendario letivo pertence
   */
  campus?: CampusFindOneInputDto;
  /**
   * Oferta de formacao do calendario letivo
   */
  ofertaFormacao?: OfertaFormacaoFindOneInputDto;
};

export type CalendarioLetivoDiaFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Data do dia no calendario
   */
  data: string;
  /**
   * Indica se o dia e letivo
   */
  diaLetivo: boolean;
  /**
   * Indica se o dia e presencial
   */
  diaPresencial: boolean;
  /**
   * Tipo do dia (presencial, feriado, sabado, etc.)
   */
  tipo:
    | 'Aula Presencial'
    | 'Aula Não Presencial (Letiva)'
    | 'Feriado'
    | 'Sábado'
    | 'Domingo'
    | 'Outro';
  /**
   * Nome do feriado (ou null se nao for)
   */
  feriado?: string | null;
  /**
   * Indica se o dia e extracurricular
   */
  extraCurricular: boolean;
  /**
   * Calendario letivo ao qual o dia pertence
   */
  calendario: CalendarioLetivoFindOneOutputDto;
};

/**
 * Tipo do dia (presencial, feriado, sabado, etc.)
 */
export type tipo2 =
  | 'Aula Presencial'
  | 'Aula Não Presencial (Letiva)'
  | 'Feriado'
  | 'Sábado'
  | 'Domingo'
  | 'Outro';

export type CalendarioLetivoDiaListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<CalendarioLetivoDiaFindOneOutputDto>;
};

export type CalendarioLetivoDiaUpdateInputDto = {
  /**
   * Indica se o dia e letivo
   */
  diaLetivo?: boolean;
  /**
   * Indica se o dia e presencial
   */
  diaPresencial?: boolean;
  /**
   * Tipo do dia (presencial, feriado, sabado, etc.)
   */
  tipo?:
    | 'Aula Presencial'
    | 'Aula Não Presencial (Letiva)'
    | 'Feriado'
    | 'Sábado'
    | 'Domingo'
    | 'Outro';
  /**
   * Nome do feriado (ou null se nao for)
   */
  feriado?: string | null;
  /**
   * Indica se o dia e extracurricular
   */
  extraCurricular?: boolean;
};

export type CalendarioLetivoEtapaFindOneOutputDto = {
  id: string;
  ofertaFormacaoPeriodoEtapaId: string;
  nomeEtapa: string;
  dataInicio: string;
  dataTermino: string;
};

export type CalendarioLetivoEtapaListOutputDto = {
  data: Array<CalendarioLetivoEtapaFindOneOutputDto>;
};

export type CalendarioLetivoEtapaBulkReplaceItemDto = {
  /**
   * ID da etapa da oferta de formacao periodo
   */
  ofertaFormacaoPeriodoEtapaId: string;
  /**
   * Data inicio da etapa
   */
  dataInicio: string;
  /**
   * Data termino da etapa
   */
  dataTermino: string;
};

export type CalendarioLetivoEtapaBulkReplaceInputDto = {
  etapas: Array<CalendarioLetivoEtapaBulkReplaceItemDto>;
};

export type CidadeListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<CidadeFindOneOutputDto>;
};

export type BlocoFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome do bloco
   */
  nome: string;
  /**
   * Codigo do bloco
   */
  codigo: string;
  /**
   * Campus do bloco
   */
  campus: CampusFindOneOutputDto;
  /**
   * Imagem de capa do bloco
   */
  imagemCapa?: ImagemFindOneOutputFromBlocoDto | null;
};

export type AmbienteFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Nome do ambiente/sala
   */
  nome: string;
  /**
   * Descricao do ambiente/sala
   */
  descricao?: string | null;
  /**
   * Codigo do ambiente/sala
   */
  codigo: string;
  /**
   * Capacidade do ambiente/sala
   */
  capacidade?: number | null;
  /**
   * Tipo do ambiente/sala. Ex.: sala aula, auditorio, laboratorio de quimica
   */
  tipo?: string | null;
  /**
   * Bloco que o ambiente/sala pertence
   */
  bloco: BlocoFindOneOutputDto;
  /**
   * Imagem de capa do ambiente
   */
  imagemCapa?: ImagemFindOneOutputFromBlocoDto | null;
};

export type AmbienteListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<AmbienteFindOneOutputDto>;
};

export type AmbienteBlocoRefInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type AmbienteCreateInputDto = {
  /**
   * Nome do ambiente/sala
   */
  nome: string;
  /**
   * Descricao do ambiente/sala
   */
  descricao?: string | null;
  /**
   * Codigo do ambiente/sala
   */
  codigo: string;
  /**
   * Capacidade do ambiente/sala
   */
  capacidade?: number | null;
  /**
   * Tipo do ambiente/sala. Ex.: sala aula, auditorio, laboratorio de quimica
   */
  tipo?: string | null;
  /**
   * Bloco que o ambiente/sala pertence
   */
  bloco: AmbienteBlocoRefInputDto;
};

export type AmbienteUpdateInputDto = {
  /**
   * Nome do ambiente/sala
   */
  nome?: string;
  /**
   * Descricao do ambiente/sala
   */
  descricao?: string | null;
  /**
   * Codigo do ambiente/sala
   */
  codigo?: string;
  /**
   * Capacidade do ambiente/sala
   */
  capacidade?: number | null;
  /**
   * Tipo do ambiente/sala. Ex.: sala aula, auditorio, laboratorio de quimica
   */
  tipo?: string | null;
  /**
   * Bloco que o ambiente/sala pertence
   */
  bloco?: AmbienteBlocoRefInputDto;
};

export type BlocoListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<BlocoFindOneOutputDto>;
};

export type BlocoCampusRefInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type BlocoCreateInputDto = {
  /**
   * Nome do bloco
   */
  nome: string;
  /**
   * Codigo do bloco
   */
  codigo: string;
  /**
   * Campus do bloco
   */
  campus: BlocoCampusRefInputDto;
};

export type BlocoUpdateInputDto = {
  /**
   * Nome do bloco
   */
  nome?: string;
  /**
   * Codigo do bloco
   */
  codigo?: string;
  /**
   * Campus do bloco
   */
  campus?: BlocoCampusRefInputDto;
};

export type AuthWhoAmIOutputDto = {
  /**
   * Usuario autenticado
   */
  usuario?: UsuarioFindOneOutputDto | null;
  /**
   * Vinculos do usuario logado
   */
  perfisAtivos: Array<PerfilFindOneOutputDto>;
};

export type AuthLoginInputDto = {
  /**
   * Matrícula
   */
  matricula: string;
  /**
   * Senha
   */
  senha: string;
};

export type AuthSessionCredentialsDto = {
  /**
   * Token de acesso
   */
  access_token?: string | null;
  /**
   * Tipo do token
   */
  token_type?: string | null;
  /**
   * Token de identificacao
   */
  id_token?: string | null;
  /**
   * Token de refresh
   */
  refresh_token?: string | null;
  /**
   * Tempo de expiracao do token
   */
  expires_in?: number | null;
  /**
   * Tempo de expiracao do token
   */
  expires_at?: number | null;
  /**
   * Estado da sessao
   */
  session_state?: string | null;
  /**
   * Escopo da autenticacao
   */
  scope?: string | null;
};

export type AuthRefreshInputDto = {
  /**
   * Token de refresh
   */
  refreshToken: string | null;
};

export type AuthCredentialsSetInitialPasswordInputDto = {
  /**
   * Matrícula
   */
  matricula: string;
  /**
   * Senha
   */
  senha: string;
};

export type AuthRecoverPasswordInputDto = {
  /**
   * E-mail
   */
  email: string;
};

export type TurmaFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Periodo da turma
   */
  periodo: string;
  /**
   * Nome da turma
   */
  nome?: string | null;
  /**
   * Curso da turma
   */
  curso: CursoFindOneOutputDto;
  /**
   * Ambiente padrao da sala de aula
   */
  ambientePadraoAula?: AmbienteFindOneOutputDto | null;
  /**
   * Imagem de capa da turma
   */
  imagemCapa?: ImagemFindOneOutputFromBlocoDto | null;
};

export type DiarioFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Situacao do diario
   */
  ativo: boolean;
  /**
   * Calendario letivo vinculado ao diario
   */
  calendarioLetivo: CalendarioLetivoFindOneOutputDto;
  /**
   * Turma vinculada ao diario
   */
  turma: TurmaFindOneOutputDto;
  /**
   * Disciplina vinculada ao diario
   */
  disciplina: DisciplinaFindOneOutputDto;
  /**
   * Ambiente padrao
   */
  ambientePadrao?: AmbienteFindOneOutputDto | null;
  /**
   * Imagem de capa do diario
   */
  imagemCapa?: ImagemFindOneOutputFromBlocoDto | null;
};

export type DiarioListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<DiarioFindOneOutputDto>;
};

export type CalendarioLetivoFindOneInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type TurmaFindOneInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type DisciplinaFindOneInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type AmbienteFindOneInputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type DiarioCreateInputDto = {
  /**
   * Situacao do diario
   */
  ativo: boolean;
  /**
   * Calendario letivo vinculado ao diario
   */
  calendarioLetivo: CalendarioLetivoFindOneInputDto;
  /**
   * Turma vinculada ao diario
   */
  turma: TurmaFindOneInputDto;
  /**
   * Disciplina vinculada ao diario
   */
  disciplina: DisciplinaFindOneInputDto;
  /**
   * Ambiente padrao
   */
  ambientePadrao?: AmbienteFindOneInputDto | null;
};

export type DiarioUpdateInputDto = {
  /**
   * Situacao do diario
   */
  ativo?: boolean;
  /**
   * Calendario letivo vinculado ao diario
   */
  calendarioLetivo?: CalendarioLetivoFindOneInputDto;
  /**
   * Turma vinculada ao diario
   */
  turma?: TurmaFindOneInputDto;
  /**
   * Disciplina vinculada ao diario
   */
  disciplina?: DisciplinaFindOneInputDto;
  /**
   * Ambiente padrao
   */
  ambientePadrao?: AmbienteFindOneInputDto | null;
};

export type DiarioProfessorFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Situacao do vinculo
   */
  situacao: boolean;
  /**
   * Perfil do usuario ao campus
   */
  perfil: PerfilFindOneOutputDto;
  /**
   * Diario vinculado
   */
  diario: DiarioFindOneOutputDto;
};

export type DiarioProfessorListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<DiarioProfessorFindOneOutputDto>;
};

export type DiarioProfessorBulkReplaceItemDto = {
  /**
   * ID do perfil (uuid)
   */
  perfilId: string;
  /**
   * Situacao do vinculo
   */
  situacao: boolean;
};

export type DiarioProfessorBulkReplaceInputDto = {
  /**
   * Lista de professores para vincular ao diario
   */
  professores: Array<DiarioProfessorBulkReplaceItemDto>;
};

export type DiarioPreferenciaAgrupamentoFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Inicio da vigencia da preferencia de agrupamento
   */
  dataInicio: string;
  /**
   * Fim da vigencia da preferencia de agrupamento
   */
  dataFim?: string | null;
  /**
   * Dia da semana (ISO 8601: 1=Segunda, 7=Domingo)
   */
  diaSemanaIso: number;
  /**
   * Quantidade de aulas seguidas
   */
  aulasSeguidas: number;
  /**
   * Diario vinculado
   */
  diario: DiarioFindOneOutputDto;
};

export type DiarioPreferenciaAgrupamentoListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<DiarioPreferenciaAgrupamentoFindOneOutputDto>;
};

export type DiarioPreferenciaAgrupamentoBulkReplaceItemDto = {
  /**
   * Inicio da vigencia da preferencia de agrupamento
   */
  dataInicio: string;
  /**
   * Fim da vigencia da preferencia de agrupamento
   */
  dataFim?: string | null;
  /**
   * Dia da semana (ISO 8601: 1=Segunda, 7=Domingo)
   */
  diaSemanaIso: number;
  /**
   * Quantidade de aulas seguidas
   */
  aulasSeguidas: number;
};

export type DiarioPreferenciaAgrupamentoBulkReplaceInputDto = {
  /**
   * Lista de preferencias de agrupamento para vincular ao diario
   */
  preferenciasAgrupamento: Array<DiarioPreferenciaAgrupamentoBulkReplaceItemDto>;
};

export type TurmaListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<TurmaFindOneOutputDto>;
};

export type TurmaCreateInputDto = {
  /**
   * Periodo da turma
   */
  periodo: string;
  /**
   * Nome da turma
   */
  nome?: string | null;
  /**
   * Curso da turma
   */
  curso: {
    [key: string]: unknown;
  };
  /**
   * Ambiente padrao da sala de aula
   */
  ambientePadraoAula?: {
    [key: string]: unknown;
  } | null;
};

export type TurmaUpdateInputDto = {
  /**
   * Periodo da turma
   */
  periodo?: string;
  /**
   * Nome da turma
   */
  nome?: string | null;
  /**
   * Curso da turma
   */
  curso?: {
    [key: string]: unknown;
  };
  /**
   * Ambiente padrao da sala de aula
   */
  ambientePadraoAula?: {
    [key: string]: unknown;
  } | null;
};

export type TurmaHorarioAulaFindOneOutputDto = {
  id: string;
  horarioAulaId: string;
  inicio: string;
  fim: string;
};

export type TurmaHorarioAulaListOutputDto = {
  data: Array<TurmaHorarioAulaFindOneOutputDto>;
};

export type TurmaHorarioAulaBulkReplaceInputDto = {
  /**
   * IDs dos horarios de aula selecionados
   */
  horarioAulaIds: Array<string>;
};

export type TurmaEventoFindOneOutputDto = {
  id: string;
  nome?: string | null;
  dataInicio: string;
  dataFim?: string | null;
  diaInteiro: boolean;
  horarioInicio: string;
  horarioFim: string;
  cor?: string | null;
  repeticao?: string | null;
  status?: string | null;
};

export type TurmaEventoListOutputDto = {
  data: Array<TurmaEventoFindOneOutputDto>;
};

export type TurmaEventoCreateInputDto = {
  /**
   * Nome do evento
   */
  nome: string;
  /**
   * Data inicio
   */
  dataInicio: string;
  dataFim?: string | null;
  /**
   * Evento ocupa o dia inteiro
   */
  diaInteiro: boolean;
  horarioInicio?: string;
  horarioFim?: string;
  cor?: string | null;
  repeticao?: string | null;
};

export type TurmaEventoUpdateInputDto = {
  nome?: string;
  dataInicio?: string;
  dataFim?: string | null;
  diaInteiro?: boolean;
  horarioInicio?: string;
  horarioFim?: string;
  cor?: string | null;
  repeticao?: string | null;
};

export type TurmaDiarioConfigurarItemDto = {
  /**
   * ID da disciplina
   */
  disciplinaId: string;
  /**
   * IDs dos professores (perfis)
   */
  professorPerfilIds?: Array<string>;
};

export type TurmaDiarioConfigurarInputDto = {
  /**
   * ID do calendario letivo
   */
  calendarioLetivoId: string;
  /**
   * Configuracao de disciplinas
   */
  diarios: Array<TurmaDiarioConfigurarItemDto>;
};

export type TurmaDiarioConfigurarOutputDto = {
  /**
   * Quantidade de diarios criados
   */
  created: number;
};

export type GerarHorarioCreateInputDto = {
  /**
   * Data inicio do periodo
   */
  dataInicio: string;
  /**
   * Data termino do periodo
   */
  dataTermino?: string | null;
  /**
   * IDs das ofertas de formacao
   */
  ofertaFormacaoIds?: Array<string>;
  /**
   * Duracao: TEMPORARIO ou PERMANENTE
   */
  duracao?: 'TEMPORARIO' | 'PERMANENTE';
};

/**
 * Duracao: TEMPORARIO ou PERMANENTE
 */
export type duracao = 'TEMPORARIO' | 'PERMANENTE';

export type GerarHorarioFindOneOutputDto = {
  /**
   * ID da solicitacao
   */
  id: string;
  /**
   * Status da solicitacao de geracao de horario
   */
  status:
    | 'SOLICITADO'
    | 'PENDENTE'
    | 'SUCESSO'
    | 'ERRO'
    | 'ACEITO'
    | 'REJEITADO';
  /**
   * Duracao: TEMPORARIO ou PERMANENTE
   */
  duracao: 'TEMPORARIO' | 'PERMANENTE';
  /**
   * Data inicio do periodo
   */
  dataInicio: string;
  /**
   * Data termino do periodo
   */
  dataTermino?: string | null;
  /**
   * Resposta do gerador de horario
   */
  respostaGerador?: {
    [key: string]: unknown;
  } | null;
  /**
   * Data de criacao da solicitacao
   */
  dateCreated: string;
};

/**
 * Status da solicitacao de geracao de horario
 */
export type status =
  | 'SOLICITADO'
  | 'PENDENTE'
  | 'SUCESSO'
  | 'ERRO'
  | 'ACEITO'
  | 'REJEITADO';

export type HorarioEdicaoSessaoOutputRestDto = {
  id: string;
  status: string;
  idUsuarioFk: string;
  dateCreated: string;
  dateUpdated: string;
};

export type HorarioEdicaoMudancaInputRestDto = {
  calendarioAgendamentoId?: string;
  tipoOperacao: 'CRIAR' | 'MOVER' | 'REMOVER';
  dados: {
    [key: string]: unknown;
  };
};

export type tipoOperacao = 'CRIAR' | 'MOVER' | 'REMOVER';

export type HorarioEdicaoMudancaOutputRestDto = {
  id: string;
  idSessaoFk: string;
  idCalendarioAgendamentoFk?: string;
  tipoOperacao: string;
  dados: {
    [key: string]: unknown;
  };
  dateCreated: string;
};

export type EstadoListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<EstadoFindOneOutputDto>;
};

export type EmpresaFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Razão social da empresa
   */
  razaoSocial: string;
  /**
   * Nome fantasia da empresa
   */
  nomeFantasia: string;
  /**
   * CNPJ sem pontuação
   */
  cnpj: string;
  /**
   * Telefone da empresa
   */
  telefone: string;
  /**
   * E-mail da empresa
   */
  email: string;
  /**
   * Endereço vinculado à empresa
   */
  endereco: EnderecoFindOneOutputDto;
  /**
   * Se a empresa está ativa
   */
  ativo: boolean;
};

export type EmpresaListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<EmpresaFindOneOutputDto>;
};

export type EmpresaCreateInputDto = {
  /**
   * Razão social da empresa
   */
  razaoSocial: string;
  /**
   * Nome fantasia da empresa
   */
  nomeFantasia: string;
  /**
   * CNPJ sem pontuação
   */
  cnpj: string;
  /**
   * Telefone da empresa
   */
  telefone: string;
  /**
   * E-mail da empresa
   */
  email: string;
  /**
   * Endereço vinculado à empresa
   */
  endereco: {
    [key: string]: unknown;
  };
};

export type EmpresaUpdateInputDto = {
  /**
   * Razão social da empresa
   */
  razaoSocial?: string;
  /**
   * Nome fantasia da empresa
   */
  nomeFantasia?: string;
  /**
   * CNPJ sem pontuação
   */
  cnpj?: string;
  /**
   * Telefone da empresa
   */
  telefone?: string;
  /**
   * E-mail da empresa
   */
  email?: string;
  /**
   * Endereço vinculado à empresa
   */
  endereco?: {
    [key: string]: unknown;
  };
};

export type Object = {
  [key: string]: unknown;
};

export type HorarioEstagioOutputDto = {
  diaSemana: number;
  horaInicio: string;
  horaFim: string;
  id: string;
};

export type EstagioFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Empresa do estágio
   */
  empresa: {
    [key: string]: unknown;
  };
  /**
   * Estagiário (opcional enquanto a vaga estiver aberta)
   */
  estagiario?: {
    [key: string]: unknown;
  } | null;
  /**
   * Carga horária semanal
   */
  cargaHoraria: number;
  /**
   * Data de início do estágio
   */
  dataInicio?: string | null;
  /**
   * Data de fim do estágio
   */
  dataFim?: string | null;
  /**
   * Status do estágio
   */
  status: 'ABERTA' | 'EM_ANDAMENTO' | 'CONCLUIDA';
  /**
   * Horários do estágio
   */
  horariosEstagio: Array<HorarioEstagioOutputDto>;
  /**
   * Se o estágio está ativo
   */
  ativo: boolean;
  /**
   * Data de criação do registro
   */
  dateCreated: string;
  /**
   * Data da última atualização do registro
   */
  dateUpdated: string;
};

/**
 * Status do estágio
 */
export type status2 = 'ABERTA' | 'EM_ANDAMENTO' | 'CONCLUIDA';

export type EstagioListOutputDto = {
  data: Array<EstagioFindOneOutputDto>;
  total: number;
  page: number;
  limit: number;
};

export type HorarioEstagioInputDto = {
  diaSemana: number;
  horaInicio: string;
  horaFim: string;
};

export type EstagioCreateInputDto = {
  /**
   * Empresa do estágio
   */
  empresa: {
    [key: string]: unknown;
  };
  /**
   * Estagiário (opcional enquanto a vaga estiver aberta)
   */
  estagiario?: {
    [key: string]: unknown;
  } | null;
  /**
   * Carga horária semanal
   */
  cargaHoraria: number;
  /**
   * Data de início do estágio
   */
  dataInicio?: string | null;
  /**
   * Data de fim do estágio
   */
  dataFim?: string | null;
  /**
   * Status do estágio
   */
  status?: 'ABERTA' | 'EM_ANDAMENTO' | 'CONCLUIDA';
  /**
   * Horários do estágio
   */
  horariosEstagio?: Array<HorarioEstagioInputDto>;
};

export type EstagioUpdateInputDto = {
  /**
   * Empresa do estágio
   */
  empresa?: {
    [key: string]: unknown;
  };
  /**
   * Estagiário (opcional enquanto a vaga estiver aberta)
   */
  estagiario?: {
    [key: string]: unknown;
  } | null;
  /**
   * Carga horária semanal
   */
  cargaHoraria?: number;
  /**
   * Data de início do estágio
   */
  dataInicio?: string | null;
  /**
   * Data de fim do estágio
   */
  dataFim?: string | null;
  /**
   * Status do estágio
   */
  status?: 'ABERTA' | 'EM_ANDAMENTO' | 'CONCLUIDA';
  /**
   * Horários do estágio
   */
  horariosEstagio?: Array<HorarioEstagioInputDto>;
};

export type EstagiarioFindOneOutputDto = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data e hora da criacao do registro
   */
  dateCreated: string;
  /**
   * Data e hora da alteracao do registro
   */
  dateUpdated: string;
  /**
   * Data e hora da exclusao do registro
   */
  dateDeleted?: string | null;
  /**
   * Perfil vinculado ao estagiário
   */
  perfil: PerfilFindOneOutputDto;
  /**
   * Curso vinculado ao estagiário
   */
  curso: CursoFindOneOutputDto;
  /**
   * Turma vinculada ao estagiário
   */
  turma: TurmaFindOneOutputDto;
  /**
   * Telefone do estagiário
   */
  telefone: string;
  /**
   * Email institucional do estagiário
   */
  emailInstitucional?: string | null;
  /**
   * Data de nascimento do estagiário
   */
  dataNascimento: string;
  /**
   * Se o estagiário está ativo
   */
  ativo: boolean;
};

export type EstagiarioListOutputDto = {
  /**
   * Metadados da busca
   */
  meta: PaginationMetaRestDto;
  /**
   * Resultados da busca
   */
  data: Array<EstagiarioFindOneOutputDto>;
};

export type EstagiarioCreateInputDto = {
  /**
   * Perfil vinculado ao estagiário
   */
  perfil: {
    [key: string]: unknown;
  };
  /**
   * Curso vinculado ao estagiário
   */
  curso: {
    [key: string]: unknown;
  };
  /**
   * Turma vinculada ao estagiário
   */
  turma: {
    [key: string]: unknown;
  };
  /**
   * Telefone do estagiário
   */
  telefone: string;
  /**
   * Email institucional do estagiário
   */
  emailInstitucional: string | null;
  /**
   * Data de nascimento do estagiário
   */
  dataNascimento: string;
};

export type EstagiarioUpdateInputDto = {
  /**
   * Perfil vinculado ao estagiário
   */
  perfil?: {
    [key: string]: unknown;
  };
  /**
   * Curso vinculado ao estagiário
   */
  curso?: {
    [key: string]: unknown;
  };
  /**
   * Turma vinculada ao estagiário
   */
  turma?: {
    [key: string]: unknown;
  };
  /**
   * Telefone do estagiário
   */
  telefone?: string;
  /**
   * Email institucional do estagiário
   */
  emailInstitucional?: string | null;
  /**
   * Data de nascimento do estagiário
   */
  dataNascimento?: string;
};

export type HorarioAulaFindOneOutputDto = {
  id: string;
  inicio: string;
  fim: string;
  horarioAulaConfiguracaoId: string;
};

export type HorarioAulaListOutputDto = {
  data: Array<HorarioAulaFindOneOutputDto>;
};

export type HorarioAulaCreateInputDto = {
  /**
   * Horario inicio (HH:MM:SS)
   */
  inicio: string;
  /**
   * Horario fim (HH:MM:SS)
   */
  fim: string;
  /**
   * ID da configuracao de horario de aula
   */
  horarioAulaConfiguracaoId: string;
};

export type HorarioAulaUpdateInputDto = {
  inicio?: string;
  fim?: string;
  horarioAulaConfiguracaoId?: string;
};

export type HorarioAulaConfiguracaoFindOneOutputDto = {
  id: string;
  dataInicio: string;
  dataFim?: string | null;
  ativo: boolean;
  campusId: string;
};

export type HorarioAulaConfiguracaoListOutputDto = {
  data: Array<HorarioAulaConfiguracaoFindOneOutputDto>;
};

export type HorarioAulaConfiguracaoCreateInputDto = {
  /**
   * Data inicio da configuracao
   */
  dataInicio: string;
  /**
   * Data fim da configuracao
   */
  dataFim?: string | null;
  /**
   * Configuracao ativa
   */
  ativo: boolean;
  /**
   * ID do campus
   */
  campusId: string;
};

export type HorarioAulaConfiguracaoUpdateInputDto = {
  dataInicio?: string;
  dataFim?: string | null;
  ativo?: boolean;
  campusId?: string;
};

export type AppControllerGetServiceInfoResponse = unknown;

export type ModalidadeFindAllData = {
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type ModalidadeFindAllResponse = ModalidadeListOutputDto;

export type ModalidadeCreateData = {
  requestBody: ModalidadeCreateInputDto;
};

export type ModalidadeCreateResponse = ModalidadeFindOneOutputDto;

export type ModalidadeFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type ModalidadeFindByIdResponse = ModalidadeFindOneOutputDto;

export type ModalidadeUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: ModalidadeUpdateInputDto;
};

export type ModalidadeUpdateResponse = ModalidadeFindOneOutputDto;

export type ModalidadeDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type ModalidadeDeleteOneByIdResponse = boolean;

export type PerfilFindAllData = {
  /**
   * Filtro por ativo
   */
  filterAtivo?: Array<string>;
  /**
   * Filtro por ID do Campus
   */
  filterCampusId?: Array<string>;
  /**
   * Filtro por cargo
   */
  filterCargo?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por ID do Usuario
   */
  filterUsuarioId?: Array<string>;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
  /**
   * ID do usuario (uuid)
   */
  usuarioId: string;
};

export type PerfilFindAllResponse = PerfilListOutputDto;

export type PerfilSetVinculosData = {
  requestBody: PerfilSetVinculosInputDto;
  /**
   * ID do usuario (uuid)
   */
  usuarioId: string;
};

export type PerfilSetVinculosResponse = PerfilListOutputDto;

export type PerfilFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type PerfilFindByIdResponse = PerfilFindOneOutputDto;

export type PerfilEnsinoByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type PerfilEnsinoByIdResponse = PerfilFindOneOutputDto;

export type UsuarioFindAllData = {
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por cargo do vinculo (ex: professor)
   */
  filterVinculosCargo?: string | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type UsuarioFindAllResponse = UsuarioListOutputDto;

export type UsuarioCreateData = {
  requestBody: UsuarioCreateInputDto;
};

export type UsuarioCreateResponse = UsuarioFindOneOutputDto;

export type UsuarioFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioFindByIdResponse = UsuarioFindOneOutputDto;

export type UsuarioUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: UsuarioUpdateInputDto;
};

export type UsuarioUpdateResponse = UsuarioFindOneOutputDto;

export type UsuarioDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioDeleteOneByIdResponse = boolean;

export type UsuarioEnsinoByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioEnsinoByIdResponse = UsuarioEnsinoOutputDto;

export type UsuarioHorarioSemanalData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data da semana desejada (YYYY-MM-DD). Qualquer dia da semana; a API calcula seg-dom.
   */
  semana: string;
};

export type UsuarioHorarioSemanalResponse = HorarioSemanalOutputDto;

export type UsuarioDisponibilidadeData = {
  campusId: string;
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioDisponibilidadeResponse = unknown;

export type UsuarioSetDisponibilidadeData = {
  campusId: string;
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioSetDisponibilidadeResponse = unknown;

export type UsuarioGetImagemCapaData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioGetImagemCapaResponse = unknown;

export type UsuarioUpdateImagemCapaData = {
  formData: {
    file: Blob | File;
  };
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioUpdateImagemCapaResponse = boolean;

export type UsuarioGetImagemPerfilData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioGetImagemPerfilResponse = unknown;

export type UsuarioUpdateImagemPerfilData = {
  formData: {
    file: Blob | File;
  };
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type UsuarioUpdateImagemPerfilResponse = boolean;

export type UsuarioEventoFindAllData = {
  /**
   * ID do usuario
   */
  id: string;
};

export type UsuarioEventoFindAllResponse = UsuarioEventoListOutputDto;

export type UsuarioEventoCreateData = {
  /**
   * ID do usuario
   */
  id: string;
  requestBody: UsuarioEventoCreateInputDto;
};

export type UsuarioEventoCreateResponse = UsuarioEventoFindOneOutputDto;

export type UsuarioEventoUpdateData = {
  /**
   * ID do evento
   */
  eventoId: string;
  /**
   * ID do usuario
   */
  id: string;
  requestBody: UsuarioEventoUpdateInputDto;
};

export type UsuarioEventoUpdateResponse = UsuarioEventoFindOneOutputDto;

export type UsuarioEventoDeleteData = {
  /**
   * ID do evento
   */
  eventoId: string;
  /**
   * ID do usuario
   */
  id: string;
};

export type UsuarioEventoDeleteResponse = boolean;

export type ArquivoFindByIdData = {
  /**
   * ID do recurso de acesso (uuid)
   */
  acessoRecursoId?: string;
  /**
   * Nome do recurso de acesso
   */
  acessoRecursoNome?: string;
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type ArquivoFindByIdResponse = unknown;

export type HorarioMescladoData = {
  /**
   * IDs das turmas, separados por virgula
   */
  ids: string;
  /**
   * IDs dos professores (perfil), separados por virgula
   */
  professorIds?: string;
  /**
   * Data da semana desejada (YYYY-MM-DD). Qualquer dia da semana; a API calcula seg-dom.
   */
  semana: string;
};

export type HorarioMescladoResponse = HorarioSemanalOutputDto;

export type HorarioEdicaoCreateResponse = HorarioEdicaoSessaoOutputRestDto;

export type HorarioEdicaoApplyChangeData = {
  requestBody: HorarioEdicaoMudancaInputRestDto;
  sessaoId: string;
};

export type HorarioEdicaoApplyChangeResponse =
  HorarioEdicaoMudancaOutputRestDto;

export type HorarioEdicaoSalvarData = {
  sessaoId: string;
};

export type HorarioEdicaoSalvarResponse = HorarioEdicaoSessaoOutputRestDto;

export type HorarioEdicaoCancelarData = {
  sessaoId: string;
};

export type HorarioEdicaoCancelarResponse = HorarioEdicaoSessaoOutputRestDto;

export type CampusFindAllData = {
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type CampusFindAllResponse = CampusListOutputDto;

export type CampusCreateData = {
  requestBody: CampusCreateInputDto;
};

export type CampusCreateResponse = CampusFindOneOutputDto;

export type CampusFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CampusFindByIdResponse = CampusFindOneOutputDto;

export type CampusUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: CampusUpdateInputDto;
};

export type CampusUpdateResponse = CampusFindOneOutputDto;

export type CampusDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CampusDeleteOneByIdResponse = boolean;

export type CursoFindAllData = {
  /**
   * Filtro por ID do Campus
   */
  filterCampusId?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Filtro por ID da Oferta de Formacao
   */
  filterOfertaFormacaoId?: Array<string>;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type CursoFindAllResponse = CursoListOutputDto;

export type CursoCreateData = {
  requestBody: CursoCreateInputDto;
};

export type CursoCreateResponse = CursoFindOneOutputDto;

export type CursoFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CursoFindByIdResponse = CursoFindOneOutputDto;

export type CursoUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: CursoUpdateInputDto;
};

export type CursoUpdateResponse = CursoFindOneOutputDto;

export type CursoDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CursoDeleteOneByIdResponse = boolean;

export type CursoGetImagemCapaData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CursoGetImagemCapaResponse = unknown;

export type CursoUpdateImagemCapaData = {
  formData: {
    file: Blob | File;
  };
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CursoUpdateImagemCapaResponse = boolean;

export type CursoDisciplinasPorPeriodoFindAllData = {
  /**
   * ID do curso
   */
  cursoId: string;
};

export type CursoDisciplinasPorPeriodoFindAllResponse =
  CursoPeriodoDisciplinaListOutputDto;

export type CursoDisciplinasPorPeriodoBulkReplaceData = {
  /**
   * ID do curso
   */
  cursoId: string;
  requestBody: CursoPeriodoDisciplinaBulkReplaceInputDto;
};

export type CursoDisciplinasPorPeriodoBulkReplaceResponse =
  CursoPeriodoDisciplinaListOutputDto;

export type OfertaFormacaoFindAllData = {
  /**
   * Filtro por ID do Campus
   */
  filterCampusId?: Array<string> | null;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por ID da Modalidade
   */
  filterModalidadeId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type OfertaFormacaoFindAllResponse = OfertaFormacaoListOutputDto;

export type OfertaFormacaoCreateData = {
  requestBody: OfertaFormacaoCreateInputDto;
};

export type OfertaFormacaoCreateResponse = OfertaFormacaoFindOneOutputDto;

export type OfertaFormacaoFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type OfertaFormacaoFindByIdResponse = OfertaFormacaoFindOneOutputDto;

export type OfertaFormacaoUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: OfertaFormacaoUpdateInputDto;
};

export type OfertaFormacaoUpdateResponse = OfertaFormacaoFindOneOutputDto;

export type OfertaFormacaoDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type OfertaFormacaoDeleteOneByIdResponse = boolean;

export type NivelFormacaoFindAllData = {
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type NivelFormacaoFindAllResponse = NivelFormacaoListOutputDto;

export type NivelFormacaoCreateData = {
  requestBody: NivelFormacaoCreateInputDto;
};

export type NivelFormacaoCreateResponse = NivelFormacaoFindOneOutputDto;

export type NivelFormacaoFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type NivelFormacaoFindByIdResponse = NivelFormacaoFindOneOutputDto;

export type NivelFormacaoUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: NivelFormacaoUpdateInputDto;
};

export type NivelFormacaoUpdateResponse = NivelFormacaoFindOneOutputDto;

export type NivelFormacaoDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type NivelFormacaoDeleteOneByIdResponse = boolean;

export type DisciplinaFindAllData = {
  /**
   * Filtro por ID dos Diarios
   */
  filterDiariosId?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type DisciplinaFindAllResponse = DisciplinaListOutputDto;

export type DisciplinaCreateData = {
  requestBody: DisciplinaCreateInputDto;
};

export type DisciplinaCreateResponse = DisciplinaFindOneOutputDto;

export type DisciplinaFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type DisciplinaFindByIdResponse = DisciplinaFindOneOutputDto;

export type DisciplinaUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: DisciplinaUpdateInputDto;
};

export type DisciplinaUpdateResponse = DisciplinaFindOneOutputDto;

export type DisciplinaDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type DisciplinaDeleteOneByIdResponse = boolean;

export type DisciplinaGetImagemCapaData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type DisciplinaGetImagemCapaResponse = unknown;

export type DisciplinaUpdateImagemCapaData = {
  formData: {
    file: Blob | File;
  };
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type DisciplinaUpdateImagemCapaResponse = boolean;

export type CalendarioEventoFindAllData = {
  filterOfertaFormacaoId: string;
  filterPeriodo: string;
  filterTurmaId: string;
  search: string;
};

export type CalendarioEventoFindAllResponse = CalendarioEventoListOutputDto;

export type CalendarioEventoCreateData = {
  requestBody: CalendarioEventoCreateInputDto;
};

export type CalendarioEventoCreateResponse = CalendarioEventoFindOneOutputDto;

export type CalendarioEventoFindByIdData = {
  id: string;
};

export type CalendarioEventoFindByIdResponse = CalendarioEventoFindOneOutputDto;

export type CalendarioEventoUpdateData = {
  id: string;
  requestBody: CalendarioEventoUpdateInputDto;
};

export type CalendarioEventoUpdateResponse = CalendarioEventoFindOneOutputDto;

export type CalendarioEventoDeleteData = {
  id: string;
};

export type CalendarioEventoDeleteResponse = boolean;

export type CalendarioLetivoFindAllData = {
  /**
   * Filtro por ano letivo
   */
  filterAno?: Array<string> | null;
  /**
   * Filtro por ID do Campus
   */
  filterCampusId?: Array<string> | null;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por ID da Oferta de Formacao
   */
  filterOfertaFormacaoId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type CalendarioLetivoFindAllResponse = CalendarioLetivoListOutputDto;

export type CalendarioLetivoCreateData = {
  requestBody: CalendarioLetivoCreateInputDto;
};

export type CalendarioLetivoCreateResponse = CalendarioLetivoFindOneOutputDto;

export type CalendarioLetivoFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CalendarioLetivoFindByIdResponse = CalendarioLetivoFindOneOutputDto;

export type CalendarioLetivoUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: CalendarioLetivoUpdateInputDto;
};

export type CalendarioLetivoUpdateResponse = CalendarioLetivoFindOneOutputDto;

export type CalendarioLetivoDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CalendarioLetivoDeleteOneByIdResponse = boolean;

export type CalendarioLetivoDiaFindAllData = {
  /**
   * ID do calendario letivo (uuid)
   */
  calendarioLetivoId: string;
  /**
   * Filtro por ano do Calendario
   */
  filterCalendarioAno?: Array<string> | null;
  /**
   * Filtro por nome do Calendario
   */
  filterCalendarioNome?: Array<string> | null;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type CalendarioLetivoDiaFindAllResponse =
  CalendarioLetivoDiaListOutputDto;

export type CalendarioLetivoDiaFindByDataData = {
  /**
   * ID do calendario letivo (uuid)
   */
  calendarioLetivoId: string;
  /**
   * Data do dia no calendario (YYYY-MM-DD)
   */
  data: string;
};

export type CalendarioLetivoDiaFindByDataResponse =
  CalendarioLetivoDiaFindOneOutputDto;

export type CalendarioLetivoDiaUpdateData = {
  /**
   * ID do calendario letivo (uuid)
   */
  calendarioLetivoId: string;
  /**
   * Data do dia no calendario (YYYY-MM-DD)
   */
  data: string;
  requestBody: CalendarioLetivoDiaUpdateInputDto;
};

export type CalendarioLetivoDiaUpdateResponse =
  CalendarioLetivoDiaFindOneOutputDto;

export type CalendarioLetivoEtapaFindAllData = {
  /**
   * ID do calendario letivo
   */
  calendarioLetivoId: string;
};

export type CalendarioLetivoEtapaFindAllResponse =
  CalendarioLetivoEtapaListOutputDto;

export type CalendarioLetivoEtapaBulkReplaceData = {
  /**
   * ID do calendario letivo
   */
  calendarioLetivoId: string;
  requestBody: CalendarioLetivoEtapaBulkReplaceInputDto;
};

export type CalendarioLetivoEtapaBulkReplaceResponse =
  CalendarioLetivoEtapaListOutputDto;

export type CalendarioLetivoDesativarData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type CalendarioLetivoDesativarResponse = boolean;

export type CidadeFindAllData = {
  /**
   * Filtro por ID do Estado
   */
  filterEstadoId?: Array<string>;
  /**
   * Filtro por nome do Estado
   */
  filterEstadoNome?: Array<string>;
  /**
   * Filtro por sigla do Estado
   */
  filterEstadoSigla?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type CidadeFindAllResponse = CidadeListOutputDto;

export type CidadeFindByIdData = {
  /**
   * Identificador do registro (numerico)
   */
  id: number;
};

export type CidadeFindByIdResponse = CidadeFindOneOutputDto;

export type AmbienteListDisponiveisResponse = unknown;

export type AmbienteFindAllData = {
  /**
   * Filtro por ID do Campus do Bloco
   */
  filterBlocoCampusId?: Array<string>;
  /**
   * Filtro por ID do Bloco
   */
  filterBlocoId?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type AmbienteFindAllResponse = AmbienteListOutputDto;

export type AmbienteCreateData = {
  requestBody: AmbienteCreateInputDto;
};

export type AmbienteCreateResponse = AmbienteFindOneOutputDto;

export type AmbienteGetDisponibilidadeData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type AmbienteGetDisponibilidadeResponse = unknown;

export type AmbienteFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type AmbienteFindByIdResponse = AmbienteFindOneOutputDto;

export type AmbienteUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: AmbienteUpdateInputDto;
};

export type AmbienteUpdateResponse = AmbienteFindOneOutputDto;

export type AmbienteDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type AmbienteDeleteOneByIdResponse = boolean;

export type AmbienteGetImagemCapaData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type AmbienteGetImagemCapaResponse = unknown;

export type AmbienteUpdateImagemCapaData = {
  formData: {
    file: Blob | File;
  };
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type AmbienteUpdateImagemCapaResponse = boolean;

export type BlocoFindAllData = {
  /**
   * Filtro por ID de Campus
   */
  filterCampusId?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type BlocoFindAllResponse = BlocoListOutputDto;

export type BlocoCreateData = {
  requestBody: BlocoCreateInputDto;
};

export type BlocoCreateResponse = BlocoFindOneOutputDto;

export type BlocoFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type BlocoFindByIdResponse = BlocoFindOneOutputDto;

export type BlocoUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: BlocoUpdateInputDto;
};

export type BlocoUpdateResponse = BlocoFindOneOutputDto;

export type BlocoDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type BlocoDeleteOneByIdResponse = boolean;

export type BlocoGetImagemCapaData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type BlocoGetImagemCapaResponse = unknown;

export type BlocoUpdateImagemCapaData = {
  formData: {
    file: Blob | File;
  };
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type BlocoUpdateImagemCapaResponse = boolean;

export type AutenticacaoWhoAmIensinoResponse = UsuarioEnsinoOutputDto;

export type AutenticacaoWhoAmIResponse = AuthWhoAmIOutputDto;

export type AutenticacaoLoginData = {
  requestBody: AuthLoginInputDto;
};

export type AutenticacaoLoginResponse = AuthSessionCredentialsDto;

export type AutenticacaoRefreshData = {
  requestBody: AuthRefreshInputDto;
};

export type AutenticacaoRefreshResponse = AuthSessionCredentialsDto;

export type AutenticacaoSetInitialPasswordData = {
  requestBody: AuthCredentialsSetInitialPasswordInputDto;
};

export type AutenticacaoSetInitialPasswordResponse = boolean;

export type AutenticacaoRequestPasswordResetData = {
  requestBody: AuthRecoverPasswordInputDto;
};

export type AutenticacaoRequestPasswordResetResponse = boolean;

export type DiarioFindAllData = {
  /**
   * Filtro por ID do Ambiente Padrao
   */
  filterAmbientePadraoId?: Array<string>;
  /**
   * Filtro por ID do Calendario Letivo
   */
  filterCalendarioLetivoId?: Array<string>;
  /**
   * Filtro por ID da Disciplina
   */
  filterDisciplinaId?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por ID da Turma
   */
  filterTurmaId?: Array<string>;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type DiarioFindAllResponse = DiarioListOutputDto;

export type DiarioCreateData = {
  requestBody: DiarioCreateInputDto;
};

export type DiarioCreateResponse = DiarioFindOneOutputDto;

export type DiarioFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type DiarioFindByIdResponse = DiarioFindOneOutputDto;

export type DiarioUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: DiarioUpdateInputDto;
};

export type DiarioUpdateResponse = DiarioFindOneOutputDto;

export type DiarioDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type DiarioDeleteOneByIdResponse = boolean;

export type DiarioProfessorFindAllData = {
  /**
   * ID do diario (uuid)
   */
  diarioId: string;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por ID do Perfil
   */
  filterPerfilId?: Array<string> | null;
  /**
   * Filtro por ID do Usuario do Perfil
   */
  filterPerfilUsuarioId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type DiarioProfessorFindAllResponse = DiarioProfessorListOutputDto;

export type DiarioProfessorBulkReplaceData = {
  /**
   * ID do diario (uuid)
   */
  diarioId: string;
  requestBody: DiarioProfessorBulkReplaceInputDto;
};

export type DiarioProfessorBulkReplaceResponse = DiarioProfessorListOutputDto;

export type DiarioPreferenciaAgrupamentoFindAllData = {
  /**
   * ID do diario (uuid)
   */
  diarioId: string;
  /**
   * Filtro por ID do Diario
   */
  filterDiarioId?: Array<string> | null;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type DiarioPreferenciaAgrupamentoFindAllResponse =
  DiarioPreferenciaAgrupamentoListOutputDto;

export type DiarioPreferenciaAgrupamentoBulkReplaceData = {
  /**
   * ID do diario (uuid)
   */
  diarioId: string;
  requestBody: DiarioPreferenciaAgrupamentoBulkReplaceInputDto;
};

export type DiarioPreferenciaAgrupamentoBulkReplaceResponse =
  DiarioPreferenciaAgrupamentoListOutputDto;

export type TurmaFindAllData = {
  /**
   * Filtro por capacidade do Ambiente Padrao de Aula
   */
  filterAmbientePadraoAulaCapacidade?: Array<string>;
  /**
   * Filtro por codigo do Ambiente Padrao de Aula
   */
  filterAmbientePadraoAulaCodigo?: Array<string>;
  /**
   * Filtro por nome do Ambiente Padrao de Aula
   */
  filterAmbientePadraoAulaNome?: Array<string>;
  /**
   * Filtro por tipo do Ambiente Padrao de Aula
   */
  filterAmbientePadraoAulaTipo?: Array<string>;
  /**
   * Filtro por ID do Campus do Curso
   */
  filterCursoCampusId?: Array<string>;
  /**
   * Filtro por ID do Curso
   */
  filterCursoId?: Array<string>;
  /**
   * Filtro por nome do Curso
   */
  filterCursoNome?: Array<string>;
  /**
   * Filtro por nome abreviado do Curso
   */
  filterCursoNomeAbreviado?: Array<string>;
  /**
   * Filtro por ID da Oferta de Formacao do Curso
   */
  filterCursoOfertaFormacaoId?: Array<string>;
  /**
   * Filtro por nome da Oferta de Formacao do Curso
   */
  filterCursoOfertaFormacaoNome?: Array<string>;
  /**
   * Filtro por slug da Oferta de Formacao do Curso
   */
  filterCursoOfertaFormacaoSlug?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por periodo da turma
   */
  filterPeriodo?: Array<string>;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type TurmaFindAllResponse = TurmaListOutputDto;

export type TurmaCreateData = {
  requestBody: TurmaCreateInputDto;
};

export type TurmaCreateResponse = TurmaFindOneOutputDto;

export type TurmaFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type TurmaFindByIdResponse = TurmaFindOneOutputDto;

export type TurmaUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: TurmaUpdateInputDto;
};

export type TurmaUpdateResponse = TurmaFindOneOutputDto;

export type TurmaDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type TurmaDeleteOneByIdResponse = boolean;

export type TurmaHorarioSemanalData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  /**
   * Data da semana desejada (YYYY-MM-DD). Qualquer dia da semana; a API calcula seg-dom.
   */
  semana: string;
};

export type TurmaHorarioSemanalResponse = HorarioSemanalOutputDto;

export type TurmaGetImagemCapaData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type TurmaGetImagemCapaResponse = unknown;

export type TurmaUpdateImagemCapaData = {
  formData: {
    file: Blob | File;
  };
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type TurmaUpdateImagemCapaResponse = boolean;

export type TurmaHorarioAulaFindAllData = {
  /**
   * ID da turma
   */
  turmaId: string;
};

export type TurmaHorarioAulaFindAllResponse = TurmaHorarioAulaListOutputDto;

export type TurmaHorarioAulaBulkReplaceData = {
  requestBody: TurmaHorarioAulaBulkReplaceInputDto;
  /**
   * ID da turma
   */
  turmaId: string;
};

export type TurmaHorarioAulaBulkReplaceResponse = TurmaHorarioAulaListOutputDto;

export type TurmaEventoFindAllData = {
  /**
   * ID da turma
   */
  turmaId: string;
};

export type TurmaEventoFindAllResponse = TurmaEventoListOutputDto;

export type TurmaEventoCreateData = {
  requestBody: TurmaEventoCreateInputDto;
  /**
   * ID da turma
   */
  turmaId: string;
};

export type TurmaEventoCreateResponse = TurmaEventoFindOneOutputDto;

export type TurmaEventoUpdateData = {
  /**
   * ID do evento
   */
  eventoId: string;
  requestBody: TurmaEventoUpdateInputDto;
  /**
   * ID da turma
   */
  turmaId: string;
};

export type TurmaEventoUpdateResponse = TurmaEventoFindOneOutputDto;

export type TurmaEventoDeleteData = {
  /**
   * ID do evento
   */
  eventoId: string;
  /**
   * ID da turma
   */
  turmaId: string;
};

export type TurmaEventoDeleteResponse = boolean;

export type TurmaDiarioConfigurarData = {
  requestBody: TurmaDiarioConfigurarInputDto;
  /**
   * ID da turma
   */
  turmaId: string;
};

export type TurmaDiarioConfigurarResponse = TurmaDiarioConfigurarOutputDto;

export type GerarHorarioCreateData = {
  requestBody: GerarHorarioCreateInputDto;
};

export type GerarHorarioCreateResponse = GerarHorarioFindOneOutputDto;

export type GerarHorarioFindByIdData = {
  /**
   * ID da solicitacao
   */
  id: string;
};

export type GerarHorarioFindByIdResponse = GerarHorarioFindOneOutputDto;

export type GerarHorarioAceitarData = {
  /**
   * ID da solicitacao
   */
  id: string;
};

export type GerarHorarioAceitarResponse = GerarHorarioFindOneOutputDto;

export type GerarHorarioRejeitarData = {
  /**
   * ID da solicitacao
   */
  id: string;
};

export type GerarHorarioRejeitarResponse = GerarHorarioFindOneOutputDto;

export type EstadoFindAllData = {
  /**
   * Filtro por ID
   */
  filterId?: Array<string> | null;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number | null;
  /**
   * Pagina de consulta
   */
  page?: number | null;
  /**
   * Busca textual
   */
  search?: string | null;
  /**
   * Ordenação
   */
  sortBy?: Array<string> | null;
};

export type EstadoFindAllResponse = EstadoListOutputDto;

export type EstadoFindByIdData = {
  /**
   * Identificador do registro (numerico)
   */
  id: number;
};

export type EstadoFindByIdResponse = EstadoFindOneOutputDto;

export type EmpresaFindAllData = {
  /**
   * Filtro por CNPJ
   */
  filterCnpj?: Array<string>;
  /**
   * Filtro por ID de endereço
   */
  filterEnderecoId?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por nome fantasia
   */
  filterNomeFantasia?: Array<string>;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type EmpresaFindAllResponse = EmpresaListOutputDto;

export type EmpresaCreateData = {
  requestBody: EmpresaCreateInputDto;
};

export type EmpresaCreateResponse = EmpresaFindOneOutputDto;

export type EmpresaFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type EmpresaFindByIdResponse = EmpresaFindOneOutputDto;

export type EmpresaUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: EmpresaUpdateInputDto;
};

export type EmpresaUpdateResponse = EmpresaFindOneOutputDto;

export type EmpresaDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type EmpresaDeleteOneByIdResponse = boolean;

export type EstagioFindAllData = {
  /**
   * Filtro por empresa
   */
  filterEmpresaId?: Object;
  /**
   * Filtro por estagiário
   */
  filterEstagiarioId?: Object;
  /**
   * Filtro por status (string ou array)
   */
  filterStatus?: Object;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type EstagioFindAllResponse = EstagioListOutputDto;

export type EstagioCreateData = {
  requestBody: EstagioCreateInputDto;
};

export type EstagioCreateResponse = EstagioFindOneOutputDto;

export type EstagioFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type EstagioFindByIdResponse = EstagioFindOneOutputDto;

export type EstagioUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: EstagioUpdateInputDto;
};

export type EstagioUpdateResponse = EstagioFindOneOutputDto;

export type EstagioDeleteData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type EstagioDeleteResponse = unknown;

export type EstagiarioFindAllData = {
  /**
   * Filtro por ID de curso
   */
  filterCursoId?: Array<string>;
  /**
   * Filtro por ID
   */
  filterId?: Array<string>;
  /**
   * Filtro por ID de perfil
   */
  filterPerfilId?: Array<string>;
  /**
   * Filtro por ID de turma
   */
  filterTurmaId?: Array<string>;
  /**
   * Limite da quantidade de resultados por pagina
   */
  limit?: number;
  /**
   * Pagina de consulta
   */
  page?: number;
  /**
   * Busca textual
   */
  search?: string;
  /**
   * Ordenacao (ex: dateCreated:ASC)
   */
  sortBy?: Array<string>;
};

export type EstagiarioFindAllResponse = EstagiarioListOutputDto;

export type EstagiarioCreateData = {
  requestBody: EstagiarioCreateInputDto;
};

export type EstagiarioCreateResponse = EstagiarioFindOneOutputDto;

export type EstagiarioFindByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type EstagiarioFindByIdResponse = EstagiarioFindOneOutputDto;

export type EstagiarioUpdateData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
  requestBody: EstagiarioUpdateInputDto;
};

export type EstagiarioUpdateResponse = EstagiarioFindOneOutputDto;

export type EstagiarioDeleteOneByIdData = {
  /**
   * Identificador do registro (uuid)
   */
  id: string;
};

export type EstagiarioDeleteOneByIdResponse = boolean;

export type NotificacaoFindAllResponse = unknown;

export type NotificacaoContagemNaoLidasResponse = unknown;

export type NotificacaoMarcarLidaData = {
  id: string;
};

export type NotificacaoMarcarLidaResponse = unknown;

export type RelatorioAulasMinistradasData = {
  cursoId: string;
  disciplinaId: string;
  perfilId: string;
  periodo: string;
  turmaId: string;
};

export type RelatorioAulasMinistradasResponse = unknown;

export type HorarioAulaFindAllData = {
  configuracaoId: string;
};

export type HorarioAulaFindAllResponse = HorarioAulaListOutputDto;

export type HorarioAulaCreateData = {
  requestBody: HorarioAulaCreateInputDto;
};

export type HorarioAulaCreateResponse = HorarioAulaFindOneOutputDto;

export type HorarioAulaFindByIdData = {
  id: string;
};

export type HorarioAulaFindByIdResponse = HorarioAulaFindOneOutputDto;

export type HorarioAulaUpdateData = {
  id: string;
  requestBody: HorarioAulaUpdateInputDto;
};

export type HorarioAulaUpdateResponse = HorarioAulaFindOneOutputDto;

export type HorarioAulaDeleteData = {
  id: string;
};

export type HorarioAulaDeleteResponse = boolean;

export type HorarioAulaConfiguracaoFindAllData = {
  campusId: string;
};

export type HorarioAulaConfiguracaoFindAllResponse =
  HorarioAulaConfiguracaoListOutputDto;

export type HorarioAulaConfiguracaoCreateData = {
  requestBody: HorarioAulaConfiguracaoCreateInputDto;
};

export type HorarioAulaConfiguracaoCreateResponse =
  HorarioAulaConfiguracaoFindOneOutputDto;

export type HorarioAulaConfiguracaoFindByIdData = {
  id: string;
};

export type HorarioAulaConfiguracaoFindByIdResponse =
  HorarioAulaConfiguracaoFindOneOutputDto;

export type HorarioAulaConfiguracaoUpdateData = {
  id: string;
  requestBody: HorarioAulaConfiguracaoUpdateInputDto;
};

export type HorarioAulaConfiguracaoUpdateResponse =
  HorarioAulaConfiguracaoFindOneOutputDto;

export type HorarioAulaConfiguracaoDeleteData = {
  id: string;
};

export type HorarioAulaConfiguracaoDeleteResponse = boolean;
