export { default as Alert, type AlertProps } from './components/Alert.vue';
export { default as Button } from './components/Button.vue';
export { default as Card, type CardProps } from './components/Card.vue';
export { default as CardAutoSkeleton } from './components/CardAutoSkeleton.vue';
export { default as CardLine } from './components/CardLine.vue';
export { default as CardSelectionDiscipline } from './components/CardSelectionDiscipline.vue';
export { default as CardSkeleton } from './components/CardSkeleton.vue';
export { default as Checkbox, type CheckboxProps } from './components/Checkbox.vue';
export { default as CheckboxSquare, type CheckboxSquareProps } from './components/CheckboxSquare.vue';
export { default as Footer } from './components/Footer.vue';
export { default as FooterButton, type FooterButtonProps, type FooterLink } from './components/FooterButton.vue';
export { default as Img, type ImgProps } from './components/Img.vue';
export { default as Loading } from './components/Loading.vue';
export * from './components/option-item';
export { default as Pagination, type PaginationProps } from './components/SimplePagination.vue';
export { default as ProgressCircular } from './components/ProgressCircular.vue';
export { default as Radio, type RadioProps } from './components/Radio.vue';
export { default as RadioCircle, type RadioCircleProps } from './components/RadioCircle.vue';
export { default as Title } from './components/Title.vue';
export { default as Toggle, type ToggleProps } from './components/Toggle.vue';
export { default as ToggleButton, type ToggleButtonProps } from './components/ToggleButton.vue';
export * from './components/toggle-item';

export { default as IconAdd } from './icons/Add.vue';
export { default as IconArrowArrow } from './icons/Arrow/Arrow.vue';
export { default as IconArrowArrowAlt } from './icons/Arrow/ArrowAlt.vue';
export { default as IconArrowArrowSidebar } from './icons/Arrow/ArrowSidebar.vue';
export { default as IconBlocks } from './icons/Blocks.vue';
export { default as IconBroom } from './icons/Broom.vue';
export { default as IconCalendarCalendar } from './icons/Calendar/Calendar.vue';
export { default as IconCalendarCalendarItems } from './icons/Calendar/CalendarItems.vue';
export { default as IconCalendarCalendarX } from './icons/Calendar/CalendarX.vue';
export { default as IconCalendarCompleteCalendar } from './icons/Calendar/CompleteCalendar.vue';
export { default as IconCalendarEvent } from './icons/Calendar/Event.vue';
export { default as IconCalendarPartialCalendar } from './icons/Calendar/PartialCalendar.vue';
export { default as IconClass } from './icons/Class.vue';
export { default as IconClassTeacher } from './icons/ClassTeacher.vue';
export { default as IconClock } from './icons/Clock.vue';
export { default as IconClockGenerate } from './icons/ClockGenerate.vue';
export { default as IconClockPermanent } from './icons/ClockPermanent.vue';
export { default as IconClockTemporary } from './icons/ClockTemporary.vue';
export { default as IconClockView } from './icons/ClockView.vue';
export { default as IconClose } from './icons/Close.vue';
export { default as IconColorThemeMoon } from './icons/ColorTheme/Moon.vue';
export { default as IconColorThemeSun } from './icons/ColorTheme/Sun.vue';
export { default as IconConfirm } from './icons/Confirm.vue';
export { default as IconCourse } from './icons/Course.vue';
export { default as IconDiary } from './icons/Diary.vue';
export { default as IconDiscipline } from './icons/Discipline.vue';
export { default as IconEdit } from './icons/Edit.vue';
export { default as IconEducator } from './icons/Educator.vue';
export { default as IconEnvironment } from './icons/Environment.vue';
export { default as IconEvent } from './icons/Event.vue';
export { default as IconExclude } from './icons/Exclude.vue';
export { default as IconExit } from './icons/Exit.vue';
export { default as IconEyeEyeOff } from './icons/Eye/EyeOff.vue';
export { default as IconEyeEyeOn } from './icons/Eye/EyeOn.vue';
export { default as IconFilePicker } from './icons/FilePicker.vue';
export { default as IconFooterBook } from './icons/Footer/Book.vue';
export { default as IconFooterGitHub } from './icons/Footer/GitHub.vue';
export { default as IconFooterHRef } from './icons/Footer/HRef.vue';
export { default as IconGenerate } from './icons/Generate.vue';
export { default as IconGroup } from './icons/Group.vue';
export { default as IconGroupedClass } from './icons/GroupedClass.vue';
export { default as IconHamburger } from './icons/Hamburger.vue';
export { default as IconHome } from './icons/Home.vue';
export { default as IconHorariosAula } from './icons/HorariosAula.vue';
export { default as IconImage } from './icons/Image.vue';
export { default as IconInfo } from './icons/Info.vue';
export { default as IconLink } from './icons/Link.vue';
export { default as IconLocale } from './icons/IconLocale.vue';
export { default as IconLocate } from './icons/Locate.vue';
export { default as IconLogout } from './icons/Logout.vue';
export { default as IconManagement } from './icons/Management.vue';
export { default as IconMenuHamburgerOff } from './icons/Menu/HamburgerOff.vue';
export { default as IconMenuHamburgerOn } from './icons/Menu/HamburgerOn.vue';
export { default as IconMenuOpen } from './icons/MenuOpen.vue';
export { default as IconModalidade } from './icons/Modalidade.vue';
export { default as IconMoreItems } from './icons/MoreItems.vue';
export { default as IconNivelFormacao } from './icons/NivelFormacao.vue';
export { default as IconNotificationCheck } from './icons/IconNotificationCheck.vue';
export { default as IconNotifications } from './icons/Notifications.vue';
export { default as IconNotificationsCheck } from './icons/NotificationsCheck.vue';
export { default as IconOthers } from './icons/Others.vue';
export { default as IconPdf } from './icons/Pdf.vue';
export { default as IconReplace } from './icons/Replace.vue';
export { default as IconReport } from './icons/Report.vue';
export { default as IconReserve } from './icons/Reserve.vue';
export { default as IconSchool } from './icons/School.vue';
export { default as IconSearch } from './icons/Search.vue';
export { default as IconSecurity } from './icons/Security.vue';
export { default as IconSettings } from './icons/Settings.vue';
export { default as IconSwap } from './icons/Swap.vue';
export { default as IconTeacherLesson } from './icons/TeacherLesson.vue';
export { default as IconUndoRedo } from './icons/UndoRedo.vue';
export { default as IconUser } from './icons/User.vue';
export { default as IconUsers } from './icons/Users.vue';
export { default as IconWarning } from './icons/Warning.vue';
