name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ci-cd-${{ github.ref }}

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASENAME: ${{ github.repository }}

jobs:
  web-ci-image:
    name: "CI: Construção e Publicação da Imagem de Container"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    environment:
      name: ci-cd-web-dev

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Autenticação no GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Construção e publicação da imagem de contêiner
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          target: web-runtime
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/web:development
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/web:cache-development
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/web:cache-development,mode=max

  web-cd-cluster:
    name: "CD: Implantação no Cluster Kubernetes"
    runs-on: deploy

    permissions:
      contents: read

    needs: [ web-ci-image ]

    environment:
      name: ci-cd-web-dev
      url: ${{ vars.DEPLOY_URL }}

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v5

      - name: Implantação da aplicação no Kubernetes
        shell: bash
        working-directory: ./k8s/development/
        run: bash ./deploy.sh
