name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'production'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        if: ${{ vars.ENABLE_PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build (and push if enabled) channel development
        if: ${{ vars.ENABLE_BUILD_IMAGE == 'true' && github.ref_name == vars.CI_DEVELOPMENT_BRANCH }}
        uses: docker/build-push-action@v6
        with:
          # build-args: 'NODE_ENV=development'
          push: ${{ vars.ENABLE_PUSH_IMAGE == 'true' }}
          tags: ${{ secrets.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG_DEVELOPMENT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build (and push if enabled) channel production
        if: ${{ vars.ENABLE_BUILD_IMAGE == 'true' && github.ref_name == vars.CI_PRODUCTION_BRANCH }}
        uses: docker/build-push-action@v6
        with:
          # build-args: 'NODE_ENV=production'
          push: ${{ vars.ENABLE_PUSH_IMAGE == 'true' }}
          tags: ${{ secrets.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG_PRODUCTION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Dispatch infrastructure deploy workflow
        if: ${{ vars.ENABLE_BUILD_IMAGE == 'true' && vars.ENABLE_PUSH_IMAGE == 'true' && vars.ENABLE_TRIGGER_DEPLOY == 'true' }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ vars.DEPLOY_OWNER }}/${{ vars.DEPLOY_REPOSITORY }}/actions/workflows/${{ vars.DEPLOY_WORKFLOW }}/dispatches \
            -d '{"ref":"${{vars.DEPLOY_BRANCH}}","inputs":{}}'
